/-
Copyright (c) 2026 The OneThird Authors. All rights reserved.
Released under the MIT License.
-/
import OneThird.Step7.SignedThreshold
import OneThird.Step7.SignConsistency
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Finset.Card
import Mathlib.Data.Finset.Image
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring

/-!
# Step 7 — Threshold cocycle on triple overlaps (`lem:cocycle`)

This file formalises the *cocycle lemma* `lem:cocycle` of `step7.tex`
§`sec:cocycle` (`step7.tex:373-644`, `lem:cocycle` at `step7.tex:391`),
the core new content of Step 7.  The lemma promotes the pairwise
signed-threshold normal forms (`lem:signed-threshold`) and sign
consistency (`lem:sign-consistency`) from S7.a into the additive
*three-way* identity

  `τ_{xz} = τ_{xy} + τ_{yz} + O(1)`

on a `(1 - o(1))`-fraction of active triples in `E⋆`.

## Paper statement (`step7.tex:391-401`)

After applying `lem:sign-consistency` to fix signs, for a
`(1 - o(1))`-fraction of active triples
`T = (e_{xy}, e_{yz}, e_{xz})` in `E⋆`,

  `τ_{xz} = τ_{xy} + τ_{yz} + O(1)`.

## Proof outline (`step7.tex:403-644`)

The argument has five steps:

1. **Shared chain window and additive identity of differences**
   (`step7.tex:420-460`).  On the triple overlap
   `Ω^{ooo}`, the signed coordinate differences
   `d_{uv}(L) = j_{uv}(L) - i_{uv}(L)` satisfy

     `d_{xz}(L) = d_{xy}(L) + d_{yz}(L) + Δ_0(T, L)`,
     `|Δ_0(T, L)| ≤ C_0` (`C_0` an absolute constant, `step7.tex:454`).

2. **Aligning signs** (`step7.tex:462-471`).  By `lem:sign-consistency`,
   `(1 - o(1))` of active triples have
   `σ̃_{xy} = σ̃_{yz} = σ̃_{xz} = +1`.

3. **Three-way threshold identity** (`step7.tex:472-495`).  Applying
   `lem:signed-threshold` to each of the three fibers yields, on
   `(1 - O(ε_2))` of the triple-overlap,

     `1_S(L) = 1{d_{xy} ≥ τ_{xy}} = 1{d_{yz} ≥ τ_{yz}}`
            ` = 1{d_{xz} ≥ τ_{xz}} + O(ε_2)`.

4. **Mismatch produces a disagreement rectangle**
   (`step7.tex:497-617`).  Writing `u := d_{xy} - τ_{xy}`,
   `v := d_{yz} - τ_{yz}`, and the *cocycle defect*
   `K_∗ := τ_{xz} - τ_{xy} - τ_{yz}`, the three-way identity reads

     `1{u ≥ 0} = 1{v ≥ 0} = 1{u + v ≥ K}`

   (with `K := K_∗ - sup_{L} Δ_0(T, L)`, so `|K - K_∗| ≤ C_0`).
   Assume for contradiction `|K| ≥ K_0`.  By symmetry assume `K ≥ K_0`.
   The rectangle

     `R := {(u, v) ∈ ℤ² : 0 ≤ u < K/2, -K/2 ≤ v < 0}`

   lies entirely inside the disagreement region
   (`1{u ≥ 0} = 1`, `1{v ≥ 0} = 0`, `1{u + v ≥ K} = 0`).

   The `ℤ²`-action generated by the two BK-shift generators `g_u, g_v`
   acts by unit translation on `(u, v)`, free and measure-preserving
   on the interior `Ω^♭ ⊆ Ω^{ooo}` of full triple-overlap mass
   `(1 - o(1)) w_T` (`step7.tex:539-571`).  Hence the pushforward
   `ν := (u, v)_∗(μ|_{Ω^♭})` is translation-invariant on `[-ct, ct]²`,
   so constant there with value `≥ w_T / (C t²)`
   (`step7.tex:572-587`, eq. `eq:pushforward-lb`).  Consequently

     `μ(Ω^{ooo} ∩ {(u, v) ∈ R}) ≥ (K/2)² · w_T / (C t²)`

   (`step7.tex:594-597`, eq. `eq:R-mass`), which exceeds the Step 2
   symmetric-difference budget `3 ε_2 · t²` unless `K` is small.

5. **Passage to `(1 - o(1))` of triples** (`step7.tex:619-643`).  Each
   *bad* active triple (cocycle defect `|K| ≥ K_0`) contributes
   `≥ c_0 w_T` to the Step 2 budget.  Summing,

     `c_0 · ∑_{bad active T} w_T ≤ 3 ε_2 · M^{(3)}`

   (`step7.tex:626-639`), so the bad active triples carry `o(M^{(3)})`
   of the active-triple mass.

## Lean formalisation

We formalise the content in cleared-denominator abstract form,
parametric in the combinatorial inputs.  All the geometric and
measure-theoretic content (the pushforward lower bound from the
`ℤ²`-action, the Step 2 symmetric-difference budget) enters as
explicit hypotheses on an abstract `TripleData` bundle.

Downstream, `lem:potential` (`step7.tex:657-669`) integrates the
cocycle along the giant component of the triple graph to produce
a single-vertex potential.
-/

namespace OneThird
namespace Step7

open Finset OneThird.Step3
open scoped BigOperators

/-! ### §1 — Triple-overlap data and cocycle defect -/

/-- **Triple-overlap combinatorial data** (`step7.tex:404-418`).

For each active triple `T`, this bundle packages the combinatorial
outputs of Step 1 (`cor:triple-overlap`) and of the signed-threshold
normal form `lem:signed-threshold` applied to the three pairwise
fibers:

* `tripleFib T` — the triple-overlap subset
  `Ω^{ooo} ⊆ fib_{xy} ∩ fib_{yz} ∩ fib_{xz}` on which the three
  coordinate systems are simultaneously valid
  (`step7.tex:410-418`);
* `uCoord T L = d_{xy}(L) - τ_{xy}` — the first coordinate shifted
  by its threshold (`step7.tex:498`);
* `vCoord T L = d_{yz}(L) - τ_{yz}` — the second coordinate shifted
  by its threshold (`step7.tex:498`);
* `cocycleDefect T = K_∗ - Δ_0-correction` — the shifted defect
  `K(T)` of `step7.tex:503`;
* `weight T = w_T` — the triple-overlap mass (`step7.tex:405-407`);
* `fiberBound T` — the per-triple fiber bound, an integer with the
  role of `t²` in the Step 2 budget (`step7.tex:598-599`). -/
structure TripleData (Triple LinExt : Type*) where
  /-- Triple-overlap subset `Ω^{ooo}`. -/
  tripleFib : Triple → Finset LinExt
  /-- First shifted coordinate `u = d_{xy} - τ_{xy}`. -/
  uCoord : Triple → LinExt → ℤ
  /-- Second shifted coordinate `v = d_{yz} - τ_{yz}`. -/
  vCoord : Triple → LinExt → ℤ
  /-- Shifted cocycle defect `K(T)` (`step7.tex:503`). -/
  cocycleDefect : Triple → ℤ
  /-- Triple-overlap weight `w_T` (`step7.tex:405-407`). -/
  weight : Triple → ℕ
  /-- Per-triple fiber bound playing the role of `t²`
  (`step7.tex:598-599`). -/
  fiberBound : Triple → ℕ

namespace TripleData

variable {Triple LinExt : Type*} [DecidableEq Triple] [DecidableEq LinExt]
  (D : TripleData Triple LinExt)

/-- **Disagreement rectangle** (`step7.tex:520-527`).

The subset of the triple overlap on which the three-rule identity
`1{u ≥ 0} = 1{v ≥ 0} = 1{u + v ≥ K}` *fails*: specifically, on
`0 ≤ u < K/2` and `-K/2 ≤ v < 0` we have `u ≥ 0` (indicator 1),
`v < 0` (indicator 0), and `u + v < 0 + 0 = 0 < K` (indicator 0,
since `K ≥ K_0 > 0`).

We use the open form `0 ≤ u ∧ v < 0 ∧ u + v < K` for the
filter condition; for `K > 0` this is a superset of the paper's
explicit rectangle and only strengthens the lower-bound argument. -/
def disagreementRect (T : Triple) : Finset LinExt :=
  (D.tripleFib T).filter (fun L =>
    0 ≤ D.uCoord T L ∧ D.vCoord T L < 0 ∧
      D.uCoord T L + D.vCoord T L < D.cocycleDefect T)

@[simp] lemma mem_disagreementRect {T : Triple} {L : LinExt} :
    L ∈ D.disagreementRect T ↔
      L ∈ D.tripleFib T ∧ 0 ≤ D.uCoord T L ∧ D.vCoord T L < 0 ∧
        D.uCoord T L + D.vCoord T L < D.cocycleDefect T := by
  simp [disagreementRect, and_assoc]

lemma disagreementRect_subset_tripleFib (T : Triple) :
    D.disagreementRect T ⊆ D.tripleFib T :=
  Finset.filter_subset _ _

/-- **Coordinate fiber** at a lattice point (`step7.tex:533`).

The set of linear extensions `L ∈ Ω^{ooo}` whose shifted coordinates
`(u(L), v(L))` equal a specified lattice point. -/
def coordFiber (T : Triple) (p : ℤ × ℤ) : Finset LinExt :=
  (D.tripleFib T).filter
    (fun L => D.uCoord T L = p.1 ∧ D.vCoord T L = p.2)

@[simp] lemma mem_coordFiber {T : Triple} {p : ℤ × ℤ} {L : LinExt} :
    L ∈ D.coordFiber T p ↔
      L ∈ D.tripleFib T ∧ D.uCoord T L = p.1 ∧ D.vCoord T L = p.2 := by
  simp [coordFiber, and_assoc]

end TripleData

/-! ### §2 — Lattice-point parameterisation of the rectangle -/

/-- **Explicit lattice rectangle** (`step7.tex:520-523`).

The set of integer points `(u₀, v₀) ∈ ℤ²` with
`0 ≤ u₀ < K/2, -K/2 ≤ v₀ < 0`.  For `K > 0`, every such point
sits in the disagreement region: `u₀ ≥ 0`, `v₀ < 0`, and
`u₀ + v₀ < K/2 + 0 < K`. -/
def rectLattice (K : ℤ) : Finset (ℤ × ℤ) :=
  ((Finset.Icc (0 : ℤ) (K - 1)) ×ˢ (Finset.Icc (-K) (-1 : ℤ))).filter
    (fun p => 2 * p.1 < K ∧ -K ≤ 2 * p.2 ∧ p.1 + p.2 < K)

lemma mem_rectLattice {K : ℤ} {p : ℤ × ℤ} :
    p ∈ rectLattice K ↔
      0 ≤ p.1 ∧ p.1 ≤ K - 1 ∧ -K ≤ p.2 ∧ p.2 ≤ -1 ∧
        2 * p.1 < K ∧ -K ≤ 2 * p.2 ∧ p.1 + p.2 < K := by
  simp [rectLattice, Finset.mem_filter, Finset.mem_product,
    Finset.mem_Icc, and_assoc]

/-- For `K > 0`, every lattice point in the `[0, K/2) × [-K/2, 0)`
rectangle satisfies the disagreement conditions
`0 ≤ u ∧ v < 0 ∧ u + v < K`. -/
lemma rectLattice_disagrees {K : ℤ} (_hK : 0 < K) {p : ℤ × ℤ}
    (hp : p ∈ rectLattice K) :
    0 ≤ p.1 ∧ p.2 < 0 ∧ p.1 + p.2 < K := by
  rw [mem_rectLattice] at hp
  refine ⟨hp.1, ?_, hp.2.2.2.2.2.2⟩
  linarith [hp.2.2.2.1]

/-- **Lattice-point count lower bound** on `rectLattice K`.

We lower-bound `|rectLattice K|` by `⌊K/2⌋²` via the injection
`(i, j) ∈ (range N)² ↦ ((i : ℤ), -(j + 1))` for `N := K / 2`.

Note: the exact count `|rectLattice K| = ⌈K/2⌉ · ⌊K/2⌋ = ⌊K²/4⌋`
differs from `K²/4` by at most `1/2` for odd `K`; using the
`⌊K/2⌋²` lower bound avoids the off-by-one and is sufficient for
the cleared-denominator downstream argument. -/
lemma rectLattice_card_lb (K : ℕ) :
    (K / 2) * (K / 2) ≤ (rectLattice (K : ℤ)).card := by
  classical
  set N : ℕ := K / 2 with hN_def
  -- `2 * N ≤ K`, the basic integer-division bound.
  have h2NleK : 2 * N ≤ K := by rw [hN_def]; omega
  let ι : ℕ × ℕ → ℤ × ℤ := fun p => ((p.1 : ℤ), -((p.2 : ℤ) + 1))
  have hι_inj : Function.Injective ι := by
    intros p q hpq
    obtain ⟨i₁, j₁⟩ := p
    obtain ⟨i₂, j₂⟩ := q
    simp only [ι, Prod.mk.injEq] at hpq
    have hi : i₁ = i₂ := by exact_mod_cast hpq.1
    have hj : j₁ = j₂ := by
      have : (j₁ : ℤ) = (j₂ : ℤ) := by linarith [hpq.2]
      exact_mod_cast this
    exact Prod.mk.injEq _ _ _ _ |>.mpr ⟨hi, hj⟩
  have himg_sub :
      (((Finset.range N) ×ˢ (Finset.range N)).image ι) ⊆
          rectLattice (K : ℤ) := by
    intro p hp
    rw [Finset.mem_image] at hp
    obtain ⟨⟨i, j⟩, hij, rfl⟩ := hp
    rw [Finset.mem_product, Finset.mem_range, Finset.mem_range] at hij
    obtain ⟨hi, hj⟩ := hij
    rw [mem_rectLattice]
    simp only [ι]
    have hiN : (i : ℤ) + 1 ≤ (N : ℤ) := by exact_mod_cast hi
    have hjN : (j : ℤ) + 1 ≤ (N : ℤ) := by exact_mod_cast hj
    have hi0 : (0 : ℤ) ≤ (i : ℤ) := by exact_mod_cast Nat.zero_le _
    have hj0 : (0 : ℤ) ≤ (j : ℤ) := by exact_mod_cast Nat.zero_le _
    have h2NleK' : 2 * (N : ℤ) ≤ (K : ℤ) := by exact_mod_cast h2NleK
    refine ⟨hi0, ?_, ?_, ?_, ?_, ?_, ?_⟩
    · linarith
    · linarith
    · linarith
    · linarith
    · linarith
    · linarith
  have hcard_image :
      (((Finset.range N) ×ˢ (Finset.range N)).image ι).card = N * N := by
    rw [Finset.card_image_of_injective _ hι_inj]
    simp [Finset.card_product, Finset.card_range]
  have := Finset.card_le_card himg_sub
  rw [hcard_image] at this
  exact this

/-! ### §3 — Pushforward bound and rectangle mass lower bound -/

section Pushforward

variable {Triple LinExt : Type*} [DecidableEq Triple] [DecidableEq LinExt]
variable (D : TripleData Triple LinExt)

/-- **Pushforward hypothesis** (`step7.tex:eq:pushforward-lb`).

Cleared-denominator form of `eq:pushforward-lb` (`step7.tex:533-537`):
for every lattice point `p` in `rectLattice K` (with `K = cocycleDefect T`),
the coordinate fiber `coordFiber T p` has at least
`c_w · weight T` elements, scaled by `fiberBound T` on the right
(playing the role of `C · t²` in `step7.tex:534`):

  `c_w · weight T ≤ c_d · fiberBound T · |coordFiber T p|`.

The paper derives this from the `ℤ²`-action pushforward
(`step7.tex:539-587`); we take it as a hypothesis on abstract
triple data. -/
def PushforwardHyp (c_w c_d : ℕ) : Prop :=
  ∀ (T : Triple), ∀ p ∈ rectLattice (D.cocycleDefect T),
    c_w * D.weight T ≤ c_d * D.fiberBound T * (D.coordFiber T p).card

/-- **Coordinate fibers are pairwise disjoint** across distinct
lattice points (different `(u, v)` values trivially yield different
fibers). -/
lemma coordFiber_pairwise_disjoint (T : Triple) :
    Set.PairwiseDisjoint
      (↑(rectLattice (D.cocycleDefect T)) : Set (ℤ × ℤ))
      (D.coordFiber T) := by
  intro p _ q _ hpq
  rw [Function.onFun, Finset.disjoint_left]
  intro L hLp hLq
  rw [D.mem_coordFiber] at hLp hLq
  apply hpq
  obtain ⟨p₁, p₂⟩ := p
  obtain ⟨q₁, q₂⟩ := q
  simp only [Prod.mk.injEq]
  refine ⟨?_, ?_⟩
  · exact hLp.2.1.symm.trans hLq.2.1
  · exact hLp.2.2.symm.trans hLq.2.2

/-- **Coordinate-fiber sum** for lattice points inside the rectangle:
the disjoint union of coordinate fibers over `rectLattice K` is
contained in the disagreement rectangle. -/
lemma biUnion_coordFiber_sub_disagreementRect {T : Triple}
    (hK : 0 < D.cocycleDefect T) :
    (rectLattice (D.cocycleDefect T)).biUnion (D.coordFiber T) ⊆
      D.disagreementRect T := by
  intro L hL
  rw [Finset.mem_biUnion] at hL
  obtain ⟨p, hp, hLp⟩ := hL
  rw [D.mem_coordFiber] at hLp
  rw [D.mem_disagreementRect]
  have hdis := rectLattice_disagrees hK hp
  refine ⟨hLp.1, ?_, ?_, ?_⟩
  · rw [hLp.2.1]; exact hdis.1
  · rw [hLp.2.2]; exact hdis.2.1
  · rw [hLp.2.1, hLp.2.2]; exact hdis.2.2

/-- **Rectangle mass lower bound via coordinate fibers**
(`step7.tex:594-597`, eq. `eq:R-mass`).

Combining the pushforward hypothesis with the lattice-point count
`|rectLattice K| ≥ ⌊K/2⌋²` gives the rectangle mass lower bound
`|disagreementRect T| ≥ ⌊K/2⌋² · (w_T / (C t²))`, i.e.

  `⌊K/2⌋² · c_w · weight T ≤ c_d · fiberBound T · |disagreementRect T|`. -/
theorem disagreement_rect_card_lb
    (c_w c_d : ℕ) (hPush : PushforwardHyp D c_w c_d)
    (T : Triple) {K : ℕ} (hK : 0 < K)
    (hKeq : D.cocycleDefect T = (K : ℤ)) :
    c_w * D.weight T * ((K / 2) * (K / 2)) ≤
      (c_d * D.fiberBound T) * (D.disagreementRect T).card := by
  classical
  -- Step 1: pairwise-disjoint biUnion cardinality is the sum of
  -- coord-fiber cardinalities.
  have hdisj : (↑(rectLattice (D.cocycleDefect T)) : Set (ℤ × ℤ)).PairwiseDisjoint
      (D.coordFiber T) :=
    coordFiber_pairwise_disjoint D T
  have hcard_biUnion :
      ((rectLattice (D.cocycleDefect T)).biUnion (D.coordFiber T)).card =
        ∑ p ∈ rectLattice (D.cocycleDefect T),
          (D.coordFiber T p).card := by
    exact Finset.card_biUnion (fun p hp q hq hpq => hdisj hp hq hpq)
  -- Step 2: the biUnion is a subset of `disagreementRect T`.
  have hKpos : 0 < D.cocycleDefect T := by rw [hKeq]; exact_mod_cast hK
  have hsub := biUnion_coordFiber_sub_disagreementRect D hKpos
  have hsub_card :
      ((rectLattice (D.cocycleDefect T)).biUnion (D.coordFiber T)).card ≤
        (D.disagreementRect T).card :=
    Finset.card_le_card hsub
  -- Step 3: apply the pushforward bound on each coord-fiber.
  have hpush_sum :
      ∑ p ∈ rectLattice (D.cocycleDefect T), (c_w * D.weight T) ≤
        ∑ p ∈ rectLattice (D.cocycleDefect T),
          c_d * D.fiberBound T * (D.coordFiber T p).card := by
    apply Finset.sum_le_sum
    intro p hp
    exact hPush T p hp
  have hpush_sum' :
      (rectLattice (D.cocycleDefect T)).card * (c_w * D.weight T) ≤
        c_d * D.fiberBound T *
          ∑ p ∈ rectLattice (D.cocycleDefect T),
            (D.coordFiber T p).card := by
    have hLHS_rewrite :
        ∑ _p ∈ rectLattice (D.cocycleDefect T), (c_w * D.weight T) =
          (rectLattice (D.cocycleDefect T)).card * (c_w * D.weight T) := by
      rw [Finset.sum_const, smul_eq_mul]
    have hRHS_rewrite :
        ∑ p ∈ rectLattice (D.cocycleDefect T),
            c_d * D.fiberBound T * (D.coordFiber T p).card =
          c_d * D.fiberBound T *
            ∑ p ∈ rectLattice (D.cocycleDefect T),
              (D.coordFiber T p).card := by
      rw [Finset.mul_sum]
    rw [hLHS_rewrite] at hpush_sum
    rw [hRHS_rewrite] at hpush_sum
    exact hpush_sum
  -- Step 4: combine with `⌊K/2⌋² ≤ |rectLattice K|`.
  rw [hKeq] at hpush_sum' hcard_biUnion hsub_card
  have hLatticeLB : (K / 2) * (K / 2) ≤ (rectLattice (K : ℤ)).card :=
    rectLattice_card_lb K
  -- Chain:
  calc c_w * D.weight T * ((K / 2) * (K / 2))
      ≤ c_w * D.weight T * (rectLattice (K : ℤ)).card :=
        Nat.mul_le_mul_left _ hLatticeLB
    _ = (rectLattice (K : ℤ)).card * (c_w * D.weight T) := by ring
    _ ≤ c_d * D.fiberBound T *
          ∑ p ∈ rectLattice (K : ℤ),
            (D.coordFiber T p).card := hpush_sum'
    _ = (c_d * D.fiberBound T) *
          ((rectLattice (K : ℤ)).biUnion (D.coordFiber T)).card := by
        rw [hcard_biUnion]
    _ ≤ (c_d * D.fiberBound T) * (D.disagreementRect T).card :=
        Nat.mul_le_mul_left _ hsub_card

end Pushforward

/-! ### §4 — Per-triple budget bound and bad-triple characterisation -/

section Budget

variable {Triple LinExt : Type*} [DecidableEq Triple] [DecidableEq LinExt]
variable (D : TripleData Triple LinExt)

/-- **Per-triple Step-2 budget** (`step7.tex:598-599`, `step7.tex:624`).

Cleared-denominator form of `3 ε_2 · min_{•} |fib_•(T)| ≤ 3 ε_2 · t²`:

  `b_d · |disagreementRect T| ≤ b_n · fiberBound T`

where `b_n / b_d ≈ 3 ε_2`.

This is the hypothesis provided by Step 2's per-fiber staircase
error (`step2.tex:prop:per-fiber`) combined with the three-way
threshold identity (`step7.tex:eq:three-rules`, `step7.tex:476-485`),
whose symmetric-difference error integrates to
`3 ε_2 · |fib|`. -/
def BudgetHyp (b_n b_d : ℕ) : Prop :=
  ∀ (T : Triple), b_d * (D.disagreementRect T).card ≤ b_n * D.fiberBound T

/-- **Per-triple cocycle bound** (cleared-denominator, squared-fiber form).

Combining the rectangle mass lower bound (from
`disagreement_rect_card_lb`) with the per-triple budget
(`BudgetHyp`) gives, for every active triple `T` with cocycle
defect `K T = K ≥ 1`,

  `b_d · c_w · weight T · ⌊K/2⌋² ≤ c_d · b_n · fiberBound T²`.

This is the per-triple version of `step7.tex:600-604`:

  `⌊K/2⌋² ≤ 3 C ε_2 · t⁴ / w_T`

after clearing denominators. -/
theorem cocycle_defect_single_triple
    (c_w c_d b_n b_d : ℕ)
    (hPush : PushforwardHyp D c_w c_d) (hBud : BudgetHyp D b_n b_d)
    (T : Triple) {K : ℕ} (hK : 0 < K)
    (hKeq : D.cocycleDefect T = (K : ℤ)) :
    b_d * (c_w * D.weight T * ((K / 2) * (K / 2))) ≤
      (c_d * D.fiberBound T) * (b_n * D.fiberBound T) := by
  have hRect := disagreement_rect_card_lb D c_w c_d hPush T hK hKeq
  have hmul_bd : b_d * (c_w * D.weight T * ((K / 2) * (K / 2))) ≤
      b_d * ((c_d * D.fiberBound T) * (D.disagreementRect T).card) :=
    Nat.mul_le_mul_left _ hRect
  have hBud_T : b_d * (D.disagreementRect T).card ≤ b_n * D.fiberBound T :=
    hBud T
  have hchain : b_d * ((c_d * D.fiberBound T) * (D.disagreementRect T).card) ≤
      (c_d * D.fiberBound T) * (b_n * D.fiberBound T) := by
    have hr : b_d * ((c_d * D.fiberBound T) * (D.disagreementRect T).card) =
        (c_d * D.fiberBound T) * (b_d * (D.disagreementRect T).card) := by ring
    rw [hr]
    exact Nat.mul_le_mul_left _ hBud_T
  exact le_trans hmul_bd hchain

/-- **Bad triples** (`step7.tex:620-623`): those whose cocycle defect
`|K(T)|` exceeds a threshold `K_0`.  We track the positive case
`K(T) ≥ K_0`; by the reflection symmetry
`u ↔ -u, S ↔ S^c` (`step7.tex:518-519`) the negative case is
symmetric and absorbed by a union bound. -/
def badTriples (triples : Finset Triple) (K₀ : ℕ) : Finset Triple :=
  triples.filter (fun T => (K₀ : ℤ) ≤ D.cocycleDefect T)

lemma mem_badTriples {triples : Finset Triple} {K₀ : ℕ} {T : Triple} :
    T ∈ badTriples D triples K₀ ↔
      T ∈ triples ∧ (K₀ : ℤ) ≤ D.cocycleDefect T := by
  simp [badTriples, Finset.mem_filter]

/-- **Active threshold relation** (`step7.tex:404-408`, `step7.tex:605`).

The active-triple assumption gives `w_T ≥ η_T · |LE|` (cleared form:
`η_d · weight T ≥ η_n · totalMass`).  Combined with
`|LE| ≥ e^{Ω(n)} ≥ fiberBound T² / constant`, this forces the RHS of
`cocycle_defect_single_triple` to be an `o(1)` fraction of the LHS.
We abstract this as a hypothesis coupling the triple to its
combinatorial parameters. -/
def ActiveTripleBound (triples : Finset Triple)
    (η_n η_d : ℕ) (totalMass : ℕ) : Prop :=
  ∀ T ∈ triples, η_n * totalMass ≤ η_d * D.weight T

end Budget

/-! ### §5 — Summed bad-triple bound and final cocycle statement -/

section Summed

variable {Triple LinExt : Type*} [DecidableEq Triple] [DecidableEq LinExt]
variable (D : TripleData Triple LinExt)

/-- **Summed budget hypothesis** (`step7.tex:626-632`).

Summing the per-triple budget (`BudgetHyp`) over active triples,
one obtains the total budget bound

  `b_d · ∑_T |disagreementRect T| ≤ b_n · ∑_T fiberBound T`.

In the paper, the RHS is bounded further by `3 ε_2 · M^{(3)}` after
changing variables from `fiberBound ≈ t²` to the triple-mass
`M^{(3)}`; we take this cleared form as input. -/
def SummedBudgetHyp (triples : Finset Triple)
    (b_n b_d : ℕ) (M3 : ℕ) : Prop :=
  b_d * ∑ T ∈ triples, (D.disagreementRect T).card ≤ b_n * M3

/-- **Summed disagreement mass from `BudgetHyp`**
(`step7.tex:628-630`).

The pointwise per-triple budget `BudgetHyp` plus a
sum-of-fiberBounds bound `∑ fiberBound T ≤ M3` implies
`SummedBudgetHyp`. -/
theorem summedBudget_of_pointwise
    (triples : Finset Triple) (b_n b_d M3 : ℕ)
    (hBud : BudgetHyp D b_n b_d)
    (hM3 : ∑ T ∈ triples, D.fiberBound T ≤ M3) :
    SummedBudgetHyp D triples b_n b_d M3 := by
  unfold SummedBudgetHyp
  calc b_d * ∑ T ∈ triples, (D.disagreementRect T).card
      = ∑ T ∈ triples, b_d * (D.disagreementRect T).card := by
        rw [Finset.mul_sum]
    _ ≤ ∑ T ∈ triples, b_n * D.fiberBound T :=
        Finset.sum_le_sum (fun T _ => hBud T)
    _ = b_n * ∑ T ∈ triples, D.fiberBound T := by rw [Finset.mul_sum]
    _ ≤ b_n * M3 := Nat.mul_le_mul_left _ hM3

/-- **Sum of bad-triple weights bounded** (`step7.tex:626-639`).

Given:

* the per-triple pushforward bound (`PushforwardHyp`),
* the summed Step-2 budget hypothesis (`SummedBudgetHyp`),
* a *uniform fiber-bound upper bound* `fiberBound T ≤ tMax`
  (the paper's `t = Θ(n)` uniformity in the rich regime),

then the bad triples (`badTriples D triples K_0`) with cocycle
defect `≥ K_0` satisfy the weighted-sum bound

  `b_d · c_w · ⌊K_0/2⌋² · ∑_{bad T} weight T  ≤
     c_d · tMax · b_n · M3`. -/
theorem sum_bad_weight_bound
    (triples : Finset Triple) (K₀ : ℕ) (hK₀ : 0 < K₀)
    (c_w c_d b_n b_d tMax M3 : ℕ)
    (hPush : PushforwardHyp D c_w c_d)
    (hSumBud : SummedBudgetHyp D triples b_n b_d M3)
    (htMax : ∀ T ∈ triples, D.fiberBound T ≤ tMax)
    (hKform : ∀ T ∈ badTriples D triples K₀,
      ∃ K : ℕ, K₀ ≤ K ∧ D.cocycleDefect T = (K : ℤ)) :
    b_d * (c_w * ((K₀ / 2) * (K₀ / 2)) *
        ∑ T ∈ badTriples D triples K₀, D.weight T) ≤
      (c_d * tMax) * (b_n * M3) := by
  classical
  -- Step 1: for each bad triple T with K = cocycleDefect T ≥ K₀,
  -- the rectangle bound gives
  --   c_w · weight T · ⌊K₀/2⌋² ≤ c_w · weight T · ⌊K/2⌋² ≤
  --     c_d · fiberBound T · |disagreementRect T|.
  have hrect_per : ∀ T ∈ badTriples D triples K₀,
      c_w * D.weight T * ((K₀ / 2) * (K₀ / 2)) ≤
        (c_d * D.fiberBound T) * (D.disagreementRect T).card := by
    intro T hT
    obtain ⟨K, hK₀K, hKeq⟩ := hKform T hT
    have hKpos : 0 < K := lt_of_lt_of_le hK₀ hK₀K
    have hfull :=
      disagreement_rect_card_lb D c_w c_d hPush T hKpos hKeq
    have hdivmono : K₀ / 2 ≤ K / 2 := Nat.div_le_div_right hK₀K
    have hmono : (K₀ / 2) * (K₀ / 2) ≤ (K / 2) * (K / 2) :=
      Nat.mul_le_mul hdivmono hdivmono
    have hmono' :
        c_w * D.weight T * ((K₀ / 2) * (K₀ / 2)) ≤
        c_w * D.weight T * ((K / 2) * (K / 2)) :=
      Nat.mul_le_mul_left _ hmono
    exact le_trans hmono' hfull
  -- Step 2: bound `c_d · fiberBound T ≤ c_d · tMax` using htMax.
  have hrect_per' : ∀ T ∈ badTriples D triples K₀,
      c_w * D.weight T * ((K₀ / 2) * (K₀ / 2)) ≤
        (c_d * tMax) * (D.disagreementRect T).card := by
    intro T hT
    have h1 := hrect_per T hT
    have hTT : T ∈ triples := by
      rw [mem_badTriples] at hT; exact hT.1
    have h2 : c_d * D.fiberBound T ≤ c_d * tMax :=
      Nat.mul_le_mul_left _ (htMax T hTT)
    have h3 : (c_d * D.fiberBound T) * (D.disagreementRect T).card ≤
        (c_d * tMax) * (D.disagreementRect T).card :=
      Nat.mul_le_mul_right _ h2
    exact le_trans h1 h3
  -- Step 3: sum over bad triples.
  have hsum : ∑ T ∈ badTriples D triples K₀,
        c_w * D.weight T * ((K₀ / 2) * (K₀ / 2)) ≤
        ∑ T ∈ badTriples D triples K₀,
          (c_d * tMax) * (D.disagreementRect T).card :=
    Finset.sum_le_sum hrect_per'
  -- LHS: factor out.
  have hLHS_eq : ∑ T ∈ badTriples D triples K₀,
        c_w * D.weight T * ((K₀ / 2) * (K₀ / 2)) =
      c_w * ((K₀ / 2) * (K₀ / 2)) *
          ∑ T ∈ badTriples D triples K₀, D.weight T := by
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intros; ring
  rw [hLHS_eq] at hsum
  -- RHS: factor out `c_d · tMax`.
  have hRHS_eq : ∑ T ∈ badTriples D triples K₀,
        (c_d * tMax) * (D.disagreementRect T).card =
      (c_d * tMax) *
        ∑ T ∈ badTriples D triples K₀, (D.disagreementRect T).card := by
    rw [Finset.mul_sum]
  rw [hRHS_eq] at hsum
  -- Extend the bad-triple sum to all of `triples` (monotonicity):
  have hextend :
      ∑ T ∈ badTriples D triples K₀, (D.disagreementRect T).card ≤
        ∑ T ∈ triples, (D.disagreementRect T).card :=
    Finset.sum_le_sum_of_subset_of_nonneg
      (Finset.filter_subset _ _) (fun _ _ _ => Nat.zero_le _)
  have hsum_ext :
      c_w * ((K₀ / 2) * (K₀ / 2)) *
          ∑ T ∈ badTriples D triples K₀, D.weight T ≤
        (c_d * tMax) *
          ∑ T ∈ triples, (D.disagreementRect T).card := by
    refine le_trans hsum ?_
    exact Nat.mul_le_mul_left _ hextend
  -- Multiply both sides of hsum_ext by b_d.
  have hsum_bd : b_d * (c_w * ((K₀ / 2) * (K₀ / 2)) *
        ∑ T ∈ badTriples D triples K₀, D.weight T) ≤
      b_d * ((c_d * tMax) *
          ∑ T ∈ triples, (D.disagreementRect T).card) :=
    Nat.mul_le_mul_left _ hsum_ext
  -- Apply the summed budget `b_d · ∑ |rect| ≤ b_n · M3`:
  change b_d * ∑ T ∈ triples, (D.disagreementRect T).card ≤ b_n * M3 at hSumBud
  have hRHS_rewrite :
      b_d * ((c_d * tMax) *
          ∑ T ∈ triples, (D.disagreementRect T).card) =
      (c_d * tMax) *
          (b_d * ∑ T ∈ triples, (D.disagreementRect T).card) := by ring
  rw [hRHS_rewrite] at hsum_bd
  have hfinal :
      (c_d * tMax) *
          (b_d * ∑ T ∈ triples, (D.disagreementRect T).card) ≤
        (c_d * tMax) * (b_n * M3) :=
    Nat.mul_le_mul_left _ hSumBud
  exact le_trans hsum_bd hfinal

/-- **Final cocycle statement** (`step7.tex:641-643`, `lem:cocycle`).

Abstract cleared-denominator form of the paper's conclusion:

  *for a `(1 - o(1))`-fraction of active triples
  `T`, `τ_{xz}(T) = τ_{xy}(T) + τ_{yz}(T) + O(1)`.*

In the cleared-denominator abstraction, this reads: under the
active-triple bound (`weight T ≥ (η_n / η_d) · M^{(3)}` for every
triple) plus the hypotheses of `sum_bad_weight_bound`, the
bad-triple weight sum is bounded by a product of the form
`b_n · M^{(3)}`, with the leading coefficient absorbing `K_0`,
`c_w`, `c_d`, `tMax`, `b_d`.  The ratio to the total mass `M^{(3)}`
is then `o(1)` whenever the small parameters `(b_n / b_d) ≈ ε_2`,
`(c_d · tMax / c_w) ≈ C t²`, and `K_0`, are related by
`ε_2 · t² / K_0² = o(1)`, i.e. `K_0² ≫ ε_2 · t²` (the paper's
choice `K_0 = C_1` absolute, with `ε_2 · t² → 0`).

We state this as the combined bad-weight bound

  `b_d · c_w · ⌊K_0/2⌋² · ∑_{bad T} weight T ≤
     c_d · tMax · b_n · M^{(3)}`. -/
theorem lem_cocycle
    (triples : Finset Triple) (K₀ : ℕ) (hK₀ : 0 < K₀)
    (c_w c_d b_n b_d tMax M3 : ℕ)
    (hPush : PushforwardHyp D c_w c_d)
    (hSumBud : SummedBudgetHyp D triples b_n b_d M3)
    (htMax : ∀ T ∈ triples, D.fiberBound T ≤ tMax)
    (hKform : ∀ T ∈ badTriples D triples K₀,
      ∃ K : ℕ, K₀ ≤ K ∧ D.cocycleDefect T = (K : ℤ)) :
    b_d * (c_w * ((K₀ / 2) * (K₀ / 2)) *
        ∑ T ∈ badTriples D triples K₀, D.weight T) ≤
      (c_d * tMax) * (b_n * M3) :=
  sum_bad_weight_bound D triples K₀ hK₀ c_w c_d b_n b_d tMax M3
    hPush hSumBud htMax hKform

/-- **Good-triple weight lower bound** (`step7.tex:641-643`,
Proposition G4 restatement).

Assuming the total active-triple weight is `∑ weight = totalW`,
the good-triple weight `∑_{good} weight T ≥ totalW - ∑_{bad} weight T`
satisfies

  `b_d · c_w · ⌊K_0/2⌋² · (totalW - ∑_{good} weight) ≤
     c_d · tMax · b_n · M3`.

Equivalently, in the rich regime the bad-triple fraction is
`o(M^{(3)})`. -/
theorem good_triple_weight_lb
    (triples : Finset Triple) (K₀ : ℕ) (hK₀ : 0 < K₀)
    (c_w c_d b_n b_d tMax M3 totalW : ℕ)
    (hPush : PushforwardHyp D c_w c_d)
    (hSumBud : SummedBudgetHyp D triples b_n b_d M3)
    (htMax : ∀ T ∈ triples, D.fiberBound T ≤ tMax)
    (hKform : ∀ T ∈ badTriples D triples K₀,
      ∃ K : ℕ, K₀ ≤ K ∧ D.cocycleDefect T = (K : ℤ))
    (htotal : ∑ T ∈ triples, D.weight T = totalW) :
    b_d * (c_w * ((K₀ / 2) * (K₀ / 2)) *
        (totalW -
          ∑ T ∈ triples \ badTriples D triples K₀, D.weight T)) ≤
      (c_d * tMax) * (b_n * M3) := by
  classical
  -- Rewrite `totalW - ∑_good = ∑_bad`.  The `sdiff` form equals
  -- `filter (¬ predicate)` on `triples`.
  have hsdiff_filter :
      triples \ badTriples D triples K₀ =
        triples.filter (fun T => ¬ ((K₀ : ℤ) ≤ D.cocycleDefect T)) := by
    unfold badTriples
    ext T
    simp only [Finset.mem_sdiff, Finset.mem_filter]
    tauto
  have hsplit :
      ∑ T ∈ triples, D.weight T =
        ∑ T ∈ badTriples D triples K₀, D.weight T +
          ∑ T ∈ triples \ badTriples D triples K₀, D.weight T := by
    rw [hsdiff_filter]
    conv_lhs => rw [← Finset.sum_filter_add_sum_filter_not triples
      (fun T => (K₀ : ℤ) ≤ D.cocycleDefect T) D.weight]
    rfl
  have hbad_sub : badTriples D triples K₀ ⊆ triples :=
    Finset.filter_subset _ _
  have heq :
      totalW - ∑ T ∈ triples \ badTriples D triples K₀, D.weight T =
        ∑ T ∈ badTriples D triples K₀, D.weight T := by
    rw [← htotal, hsplit]
    omega
  rw [heq]
  exact lem_cocycle D triples K₀ hK₀ c_w c_d b_n b_d tMax M3
    hPush hSumBud htMax hKform

end Summed

end Step7
end OneThird
