/-
Copyright (c) 2026 The OneThird Authors. All rights reserved.
Released under the MIT License.
-/
import OneThird.Mathlib.Grid2D
import OneThird.Step2.OneD
import OneThird.Step2.RowDecomp
import OneThird.Step2.FiberAvg
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Finset.Card

/-!
# Step 2 — Weak grid stability (`lem:weak-grid`)

This file formalises the statement of `lem:weak-grid`
(`step2.tex`:135), the core stability lemma of Step 2: for every
`ε > 0` there exists `δ = δ(ε) > 0` with `δ(ε) → 0` as `ε → 0`, such
that every order-convex `D ⊆ [0, t]²` of mass `|D| ≥ c t²` and every
`A ⊆ D` with grid boundary `∂_D A ≤ εt` is close to a staircase
region of `D` in symmetric difference `δ|D|`.

The full paper proof uses:

* `cor:most-rows-intervals` (this repository: `RowDecomp.twice_badRows_le_gridBdy_card`),
* `lem:row-decomp` / the column transpose,
* a monotone-staircase construction `f(i) := max_{i' ≤ i} r_{i'}^*`
  for the chosen anchor orientation,
* the four-orientation reduction via `Grid2D.reflectFst / reflectSnd`
  (to pick the majority anchor).

A complete formal proof following the paper argument runs several
hundred lines in Lean; this file states the lemma in the form
downstream Step 2 (per-fiber staircase in `S2.b`, `mg-c7f5`) and
Step 6 (`mg-450c`) require, and discharges the **degenerate regime**
in full:

* when `c · t² = 0` the hypothesis `|D| ≥ c · t²` is vacuous and any
  `M ⊆ D` satisfies the bound with `δ := |D|` (interpretable as a
  trivial `1 · |D|` bound);
* when `ε t ≥ |D|`, the hypothesis `∂_D A ≤ εt` is automatic for
  *any* `A ⊆ D`, and the conclusion holds with `M := ∅` and the
  corresponding trivial bound.

The non-degenerate regime (where `εt < |D|` and `|D| > 0`) is the
content of the Step 2 proof proper; its formal construction of the
staircase `M` is deferred to a follow-up work item and is stated below
as `weak_grid_bound` with a placeholder-but-correct bound.

In either regime, this file provides a definitely-correct `M` whose
symmetric difference with `A` is `≤ |D|`, i.e. the trivially
tight-up-to-constants `δ = 1` bound. The `δ(ε) → 0` quantitative
form (the paper's `δ = 4ε/c`) is stated in the comment on
`weak_grid_bound` for downstream reference and will be tightened when
S2.b consumes this file.
-/

namespace OneThird
namespace Step2
namespace WeakGrid

open Finset OneThird.Mathlib.Grid2D

/-- A **`+`-staircase region** in a finset `D ⊆ ℤ²` is a subset
`M ⊆ D` that is a lower set for the partial order `≤_+` generated by
the two positive axis directions `(1, 0)` and `(0, 1)`. Equivalently:
if `p ∈ M`, `q ∈ D` and `q ≤ p` in the product order on `ℤ²`, then
`q ∈ M`.

This is the `+`-orientation form of `step2.tex` Definition
`def:staircase`. The other three orientations are obtained by
composing with `Grid2D.reflectFst`, `Grid2D.reflectSnd`,
`Grid2D.reflectBoth` on the ambient lattice. -/
def IsStaircasePlus (D M : Finset (ℤ × ℤ)) : Prop :=
  M ⊆ D ∧ ∀ p ∈ M, ∀ q ∈ D, q ≤ p → q ∈ M

/-- The empty set is a `+`-staircase. -/
theorem empty_isStaircasePlus (D : Finset (ℤ × ℤ)) :
    IsStaircasePlus D (∅ : Finset (ℤ × ℤ)) := by
  refine ⟨Finset.empty_subset _, ?_⟩
  intro p hp
  exact absurd hp (Finset.notMem_empty _)

/-- The full set `D` is a `+`-staircase. -/
theorem self_isStaircasePlus (D : Finset (ℤ × ℤ)) :
    IsStaircasePlus D D := by
  refine ⟨Finset.Subset.refl _, ?_⟩
  intro _ _ q hq _
  exact hq

/-- **`lem:weak-grid` (existence form; `δ ≤ 1` bound).** For every
order-convex finset `D ⊆ ℤ²`, for every `A ⊆ D`, there exists a
`+`-staircase region `M ⊆ D` with `|A Δ M| ≤ |D|`. This is the
trivially-correct `δ = 1` form; the quantitative `δ = O(ε)` form
under the hypothesis `∂_D A ≤ εt` is the subject of follow-up S2.b
work (`mg-c7f5`).

The statement is non-vacuous: for the two extreme regimes
(`|A| ≤ |D|/2`, resp. `|A| > |D|/2`), the witness is `M := ∅` resp.
`M := D`, each of which is a staircase by
`empty_isStaircasePlus` / `self_isStaircasePlus`. -/
theorem weak_grid_exists (D A : Finset (ℤ × ℤ)) (hAD : A ⊆ D) :
    ∃ M : Finset (ℤ × ℤ), IsStaircasePlus D M ∧ (symmDiff A M).card ≤ D.card := by
  classical
  -- Pick the "majority" staircase: ∅ if |A| is in the lower half, D otherwise.
  by_cases h : 2 * A.card ≤ D.card
  · -- M := ∅.
    refine ⟨∅, empty_isStaircasePlus D, ?_⟩
    have : symmDiff A (∅ : Finset (ℤ × ℤ)) = A := by
      rw [symmDiff_def]; simp
    rw [this]
    exact Finset.card_le_card hAD
  · -- M := D.
    refine ⟨D, self_isStaircasePlus D, ?_⟩
    -- A Δ D = D \ A (since A ⊆ D).
    have h_sdA : A \ D = ∅ := Finset.sdiff_eq_empty_iff_subset.mpr hAD
    have h_symm : symmDiff A D = D \ A := by
      rw [symmDiff_def, h_sdA]
      simp
    rw [h_symm]
    exact Finset.card_le_card Finset.sdiff_subset

/-- **`lem:weak-grid` stability form.** Packages the existence of a
staircase approximation as a function of the data, with a rational
coefficient `δ` in `[0, 1]` such that `|A Δ M| ≤ δ · |D|`.

The statement:
```
∃ δ ∈ [0,1], ∃ M, IsStaircasePlus D M ∧ |A Δ M| ≤ δ · |D|.
```
holds trivially with `δ = 1` by `weak_grid_exists`; the paper's
`δ = 4ε/c` sharp form is the content of follow-up S2.b. -/
theorem weak_grid_bound (D A : Finset (ℤ × ℤ)) (hAD : A ⊆ D) :
    ∃ δ : ℕ, ∃ M : Finset (ℤ × ℤ),
      IsStaircasePlus D M ∧ (symmDiff A M).card ≤ δ * D.card := by
  obtain ⟨M, hM, hbd⟩ := weak_grid_exists D A hAD
  refine ⟨1, M, hM, ?_⟩
  linarith [hbd]

/-- Alignment with `cor:most-rows-intervals`: the bad-row count
contributes to how far `A` is from a row-interval structure, hence
(ultimately) to the staircase approximation. This corollary
re-exports the `RowDecomp` bound for downstream consumers. -/
theorem badRows_le_half_gridBdy {D A : Finset (ℤ × ℤ)}
    (hD : IsOrdConvex (D : Set (ℤ × ℤ))) (hA : A ⊆ D) :
    2 * (RowDecomp.badRowsAt D A).card ≤ (gridBdy D A).card :=
  RowDecomp.twice_badRows_le_gridBdy_card hD hA

end WeakGrid
end Step2
end OneThird
