#!/usr/bin/env /usr/bin/python3
"""mg-bcd7 -- FINISH mg-72e4's one unmeasured computation:  beta~_5(Gamma(P)) for the
n = 7, c = 1 height-1 class (42 of 227892 labelled vertices).

WHAT WAS LEFT OPEN

mg-72e4 (merged 75fb81dcffa4) measured beta~_{n-c-1}(Gamma(P)) for every height-1 iso class
at n <= 7 except one.  Its own words:

    n=7 c=1 class (42 of 227892 labelled vertices) is OVER CAP: Gamma has 30 vertices and
    needs a dim-7 skeleton of 2075235 faces; a targeted run built the skeleton but the rank
    computation had not returned when this was submitted, so beta~_5 for that class is
    UNMEASURED.

The rank computation it was running is on boundary matrices of size 362740 x 105032 and
977320 x 362740 with ~7 non-zeros per column.  Sparse elimination on those fills in; that
run was not going to return.  This instrument does NOT retry it.  It replaces it with an
exact reduction that leaves three matrices of 120, 1680 and 10920 generators.

THE REDUCTION

P = {(0,1)} on [7] (the c=1 height-1 class, up to iso).  Write V = {2,3,4,5,6}, m = |V| = 5.
mg-72e4's atoms_of_upper(P,7) returns 30 atoms, each of the form tc(P u {r}) for a single
added relation r; the 30 r's are

    A = the 20 arcs inside V,     B = {(0,v) : v in V},     C = {(v,1) : v in V}.

A subset S of atoms is a face of Gamma(P) iff tc(P u S) is a NON-TOTAL partial order.
Two observations turn that into a product:

 (1) ACYCLICITY IS CARRIED BY A ALONE.  0 has no in-arc and 1 has no out-arc among the 30,
     so every directed cycle lies inside V.  Hence tc(P u S) is a partial order iff S n A
     is an acyclic digraph on V.  So the "partial order" half of the predicate defines

         X  :=  sigma(B u C)  *  K_m,        K_m := acyclic subsets of the arcs on V,

     the join of a FULL SIMPLEX on the 10 vertices B u C with K_m.  A join with a non-empty
     simplex is a cone, so X is CONTRACTIBLE.

 (2) TOTALITY IS A FILTER GENERATED IN ONE DEGREE.  tc(P u S) is total iff it is the linear
     order 0 < v1 < ... < vm < 1 for some ordering of V (0 must be the minimum and 1 the
     maximum, again because 0 is a source and 1 is a sink).  Its cover arcs
     (0,v1),(v1,v2),...,(v_{m-1},v_m),(v_m,1) are m+1 atoms and all m+1 are needed.  So the
     excluded faces are exactly the filter F generated by m! sets of size m+1, i.e. 120
     faces of DIMENSION 5 at n = 7 -- and 5 = n-c-1 is precisely the degree in question.

     Gamma(P) = X \\ F.

Because X is contractible the long exact sequence of the pair (X, Gamma) gives

         H~_d(Gamma)  ~=  H_{d+1}(X, Gamma)        for every d,

and the relative chain complex is free on F, which is empty below dimension m = n-2.  So the
target degree needs only C_5(F), C_6(F), C_7(F) -- 120, 1680 and 10920 generators.

THE ANSWER MEASURED HERE:  beta~_5(Gamma(P); Q) = 0, and beta~_4 = 0 as well.

RATIONAL, NOT CONTRACTIBLE.  This is a rational Betti number.  It says H~_5(Gamma; Q) = 0.
It does not say Gamma is contractible and this instrument does not claim that.  The primes
used are listed in the report under "primes"; the rational conclusion does not rest on
prime agreement (see Sec. RATIONAL BOUND in the report and the comment on rational_bound
below).

Run:  /usr/bin/python3 scripts/compat_geom_mgbcd7_n7c1_beta5.py
Env:  MGBCD7_SKELETON_DIM   highest dimension of the n=7 direct skeleton sweep (default 7,
                            the full one mg-72e4 built; set lower for a fast smoke run)
      MGBCD7_EXTEND_NMAX    highest n for the c=1 extension sweep (default 9; n=10 was not
                            attempted -- the size-(m+3) layer of the filter is ~19M faces)
"""

import itertools
import json
import os
import sys
import time
from collections import defaultdict

# Primes used for every rank in this instrument.  2,3,5,7 are here deliberately: mg-e08a's
# documented trap is calling a two-large-prime agreement a rational Betti number, and small
# primes are where p-torsion would actually show up.
PRIMES = (2, 3, 5, 7, 46337, 999983, 1000003)


# ------------------------------------------------------------------ posets (re-implemented)
def tc(pairs, n):
    """Transitive closure of a relation on range(n); None if it has a cycle.

    Deliberately re-implemented rather than imported from mg-72e4's script: the whole point
    of this item is to check mg-72e4's setup, not to inherit it.
    """
    adj = [0] * n
    for (a, b) in pairs:
        if a == b:
            return None
        adj[a] |= 1 << b
    for k in range(n):
        bit = 1 << k
        for i in range(n):
            if adj[i] & bit:
                adj[i] |= adj[k]
    for i in range(n):
        if adj[i] & (1 << i):
            return None
    return frozenset((i, j) for i in range(n) for j in range(n) if adj[i] >> j & 1)


def is_total(P, n):
    return len(P) == n * (n - 1) // 2


def atoms_of_upper(P, n):
    """Minimal elements of upP \\ {P} inside PPF_n -- the distinct non-total tc(P u {r})."""
    comp = set()
    for (a, b) in P:
        comp.add((a, b) if a < b else (b, a))
    inc = [(i, j) for i in range(n) for j in range(i + 1, n) if (i, j) not in comp]
    out = {}
    for (x, y) in inc:
        for r in ((x, y), (y, x)):
            Q = tc(P | {r}, n)
            if Q is None or is_total(Q, n):
                continue
            out.setdefault(Q, r)
    keys = list(out)
    minimal = [Q for Q in keys if not any(R < Q for R in keys)]
    return sorted(minimal, key=lambda Q: (len(Q), sorted(Q)))


def binom(a, b):
    if b < 0 or b > a:
        return 0
    r = 1
    for i in range(b):
        r = r * (a - i) // (i + 1)
    return r


# ---------------------------------------------------------------------------- linear algebra
def rank_mod_p(cols, p):
    """Rank over F_p of a sparse matrix given as a list of {row: coeff} columns."""
    pivots = {}
    rank = 0
    for col in cols:
        c = {r: v % p for r, v in col.items() if v % p}
        while c:
            r = max(c)
            if r not in pivots:
                inv = pow(c[r], p - 2, p)
                pivots[r] = {rr: (vv * inv) % p for rr, vv in c.items()}
                rank += 1
                break
            f = c[r]
            pr = pivots[r]
            for rr, vv in pr.items():
                nv = (c.get(rr, 0) - f * vv) % p
                if nv:
                    c[rr] = nv
                elif rr in c:
                    del c[rr]
    return rank


def boundary_cols(hi_faces, lo_index):
    """Columns of the boundary map on a set of faces.  A facet missing from lo_index is
    dropped -- which is exactly the RELATIVE boundary when lo_index lists only F-faces."""
    cols = []
    for f in hi_faces:
        col = {}
        for i in range(len(f)):
            j = lo_index.get(f[:i] + f[i + 1:])
            if j is None:
                continue
            col[j] = col.get(j, 0) + (1 if i % 2 == 0 else -1)
        cols.append(col)
    return cols


def betti_from_faces(faces_by_size, p):
    """Reduced Betti numbers of a full simplicial complex given as size -> list of sorted
    tuples, using the AUGMENTED complex (C_{-1} = field on the empty face)."""
    if not faces_by_size:
        return {-1: 1}
    smax = max(faces_by_size)
    index = {k: {f: i for i, f in enumerate(v)} for k, v in faces_by_size.items()}
    index[0] = {(): 0}
    ranks = {}
    for k in range(1, smax + 1):
        ranks[k] = rank_mod_p(boundary_cols(faces_by_size.get(k, []), index.get(k - 1, {})), p)
    betti = {}
    for k in range(0, smax + 1):
        ndim = 1 if k == 0 else len(faces_by_size.get(k, []))
        betti[k - 1] = ndim - ranks.get(k, 0) - ranks.get(k + 1, 0)
    return betti


# ------------------------------------------------------- Gamma by mg-72e4's own DFS predicate
def gamma_dfs(P, n, atoms, dmax, visit=None):
    """mg-72e4's gamma_faces, but counting (and optionally visiting) instead of storing:
    the n=7 dim-7 skeleton is millions of faces and there is no reason to hold them.

    Face test is the ORIGINAL one -- tc(P u UA) is a non-total partial order -- computed
    from scratch on [n], not from any factorisation this instrument derives."""
    m = len(atoms)
    counts = defaultdict(int)

    def rec(prefix, cur):
        d = len(prefix) - 1
        counts[d] += 1
        if visit is not None:
            visit(prefix)
        if d >= dmax:
            return
        for j in range(prefix[-1] + 1, m):
            U = cur | atoms[j]
            Q = tc(U, n)
            if Q is None or is_total(Q, n):
                continue
            rec(prefix + [j], Q)

    for i in range(m):
        rec([i], atoms[i])
    return dict(counts)


# ------------------------------------------------------------------- the structural model
class C1Model(object):
    """The X \\ F model of Gamma(P) for the c=1 height-1 class P = {(0,1)} on [n]."""

    def __init__(self, n):
        self.n = n
        self.m = n - 2
        self.V = list(range(2, n))
        self.A = [(a, b) for a in self.V for b in self.V if a != b]
        self.B = [(0, v) for v in self.V]
        self.C = [(v, 1) for v in self.V]
        self.P = frozenset({(0, 1)})
        self.atoms = atoms_of_upper(self.P, n)
        # atom -> the single relation it adds, and the index used by the DFS above
        self.rel_of_atom = [sorted(Q - self.P)[0] for Q in self.atoms]
        self.index_of_rel = {r: i for i, r in enumerate(self.rel_of_atom)}

    # ---- (1) acyclicity carried by A alone
    def acyclic(self, rels):
        adj = {v: 0 for v in self.V}
        for (a, b) in rels:
            if a in adj and b in adj:
                adj[a] |= 1 << b
        for k in self.V:
            bit = 1 << k
            for i in self.V:
                if adj[i] & bit:
                    adj[i] |= adj[k]
        return not any(adj[i] >> i & 1 for i in self.V)

    # ---- (2) the filter generators: the m! maximal chains 0 < v1 < ... < vm < 1
    def generators(self):
        out = []
        for perm in itertools.permutations(self.V):
            rels = [(0, perm[0])] + [(perm[i], perm[i + 1]) for i in range(self.m - 1)] \
                   + [(perm[-1], 1)]
            out.append(frozenset(self.index_of_rel[r] for r in rels))
        return out

    def filter_from(self, gens, kmax):
        """The filter inside X generated by an arbitrary set of generating faces, by size.
        Used both for the real filter and for the perturbed one in the negative control."""
        g = len(next(iter(gens)))
        F = {k: set() for k in range(g, kmax + 1)}
        nat = len(self.atoms)
        for t in gens:
            F[g].add(t)
            rest = [i for i in range(nat) if i not in t]
            for extra in range(1, kmax - g + 1):
                for add in itertools.combinations(rest, extra):
                    s = t | set(add)
                    if self.in_X(s):
                        F[g + extra].add(s)
        return {k: sorted(tuple(sorted(s)) for s in v) for k, v in F.items()}

    def in_X(self, idxs):
        return self.acyclic([self.rel_of_atom[i] for i in idxs])

    # ---- closed-form face count of X = sigma(B u C) * K_m, by size
    def acyclic_profile(self):
        """a[i] = number of acyclic subsets of the arcs on V of size i (exhaustive)."""
        a = [0] * (len(self.A) + 1)
        for mask in range(1 << len(self.A)):
            S = [self.A[i] for i in range(len(self.A)) if mask >> i & 1]
            if self.acyclic(S):
                a[len(S)] += 1
        return a

    def X_size_counts(self, kmax, a=None):
        a = self.acyclic_profile() if a is None else a
        nbc = 2 * self.m
        return {k: sum(binom(nbc, j) * (a[k - j] if 0 <= k - j < len(a) else 0)
                       for j in range(0, nbc + 1))
                for k in range(0, kmax + 1)}

    # ---- the filter F, by size, up to a cap
    def filter_faces(self, kmax):
        return self.filter_from(self.generators(), kmax)

    # ---- H_*(X, Gamma) in the two degrees that matter
    def relative_ranks(self, F, p):
        """rank of the relative boundary d_k : C_{k-1}(F) -> C_{k-2}(F), keyed by SIZE k."""
        idx = {k: {f: i for i, f in enumerate(v)} for k, v in F.items()}
        out = {}
        for k in sorted(F):
            if k - 1 not in idx:
                continue
            out[k] = rank_mod_p(boundary_cols(F[k], idx[k - 1]), p)
        return out


# --------------------------------------------------------------------------------- controls
def facets_to_faces(facets):
    fs = set()
    for F in facets:
        for k in range(1, len(F) + 1):
            for s in itertools.combinations(sorted(F), k):
                fs.add(s)
    by = defaultdict(list)
    for s in fs:
        by[len(s)].append(s)
    return {k: sorted(v) for k, v in by.items()}


def control_known_homology(report):
    """C0: the rank/Betti machinery against complexes whose homology is known."""
    ok = []
    for k in range(1, 6):                                    # boundary of a k-simplex = S^{k-1}
        b = betti_from_faces(facets_to_faces(list(itertools.combinations(range(k + 1), k))),
                             PRIMES[-1])
        ok.append(("bd_simplex_%d" % k, b.get(k - 1) == 1 and
                   all(v == 0 for d, v in b.items() if d != k - 1)))
    torus = [tuple(sorted(((i + a) % 7 for a in s))) for i in range(7)
             for s in ((0, 1, 3), (0, 1, 5))]
    b = betti_from_faces(facets_to_faces(torus), PRIMES[-1])
    ok.append(("torus_Z7_beta_0_1_2_is_0_2_1",
               (b.get(0), b.get(1), b.get(2)) == (0, 2, 1)))
    # F_2 must SEE the torsion the large primes cannot: RP^2 has beta_1 = 0 over Q, 1 over F_2
    rp2 = [(0, 1, 2), (0, 2, 3), (0, 1, 5), (0, 4, 5), (0, 3, 4), (1, 2, 4), (1, 3, 4),
           (1, 3, 5), (2, 3, 5), (2, 4, 5)]
    bq = betti_from_faces(facets_to_faces(rp2), 1000003)
    b2 = betti_from_faces(facets_to_faces(rp2), 2)
    ok.append(("RP2_rational_acyclic", all(v == 0 for v in bq.values())))
    ok.append(("RP2_seen_by_F2", b2.get(1) == 1 and b2.get(2) == 1))
    report["C0_known_homology"] = {k: v for k, v in ok}
    return [k for k, v in ok if not v]


def relative_two_degrees(F, g, p):
    """The two numbers the whole instrument turns on, for a filter F generated in size g
    inside a CONTRACTIBLE X:

        b_below = |C_{g-1}(F)| - rank(d_g)                 ~= beta~_{g-2}(X \\ F)
        b_at    = (|C_g(F)| - rank(d_g)) - rank(d_{g+1})   ~= beta~_{g-1}(X \\ F)

    (sizes: C_{g-1}(F) is spanned by the size-g faces of F, C_g(F) by the size-(g+1) ones.)
    """
    idx = {k: {f: i for i, f in enumerate(v)} for k, v in F.items()}
    r1 = rank_mod_p(boundary_cols(F.get(g + 1, []), idx.get(g, {})), p)
    r2 = rank_mod_p(boundary_cols(F.get(g + 2, []), idx.get(g + 1, {})), p)
    return (len(F.get(g, [])) - r1), ((len(F.get(g + 1, [])) - r1) - r2), r1, r2


def _simplex_filter(N, gens, kmax):
    """Filter inside the full simplex on N vertices generated by `gens`, by size."""
    g = len(gens[0])
    F = {k: set() for k in range(g, kmax + 1)}
    for t in gens:
        t = frozenset(t)
        F[g].add(t)
        rest = [i for i in range(N) if i not in t]
        for extra in range(1, kmax - g + 1):
            for add in itertools.combinations(rest, extra):
                F[g + extra].add(t | set(add))
    return {k: sorted(tuple(sorted(s)) for s in v) for k, v in F.items()}


def _synthetic_cases():
    """(name, N, g, generators) -- X = full simplex on N vertices (contractible, like the
    real X); F = filter generated by those size-g faces; Gamma = X \\ F.

    Chosen so that between them the two slots the instrument reads,

        b_below ~= beta~_{g-2}(Gamma)   and   b_at ~= beta~_{g-1}(Gamma),

    are each non-zero somewhere, and so that one case has homology only F_2 can see.
    """
    cases = []
    for N, g in ((7, 4), (8, 5)):
        cases.append(("SKEL_%d_%d" % (N, g), N, g, list(itertools.combinations(range(N), g))))
        cases.append(("STAR_%d_%d" % (N, g), N, g,
                      [(0,) + c for c in itertools.combinations(range(1, N), g - 1)]))
    # a 4-cycle: minimal non-faces {0,1} and {2,3}; beta~_1 = 1 sits in the b_at slot
    cases.append(("CYCLE4", 4, 2, [(0, 1), (2, 3)]))
    # the 7-vertex torus: 14 triangles, complete 1-skeleton.  beta~_1 = 2 AND beta~_2 = 1
    # over Q -- both slots non-zero at once, with all minimal non-faces of size 3.
    tri = set(tuple(sorted(((i + a) % 7 for a in s))) for i in range(7)
              for s in ((0, 1, 3), (0, 1, 5)))
    cases.append(("TORUS_Z7", 7, 3,
                  [t for t in itertools.combinations(range(7), 3) if t not in tri]))
    # the 6-vertex RP^2: rationally acyclic, but beta~_1 = beta~_2 = 1 over F_2.  This is the
    # mg-e08a trap in control form -- a case where a large-prime zero is NOT the whole story.
    rp2 = set([(0, 1, 2), (0, 2, 3), (0, 1, 5), (0, 4, 5), (0, 3, 4), (1, 2, 4), (1, 3, 4),
               (1, 3, 5), (2, 3, 5), (2, 4, 5)])
    cases.append(("RP2_6", 6, 3,
                  [t for t in itertools.combinations(range(6), 3) if t not in rp2]))
    return cases


def control_relative_machinery(report):
    """C1: the RELATIVE route against a DIRECT full-complex computation of the SAME Gamma.

    This is the control that decides whether the reduction used for the real class is
    trustworthy, so it is run on complexes whose homology is independently known and, in
    particular, NON-ZERO in the slot the real answer is read from.  An instrument that
    silently returns 0 in that slot cannot pass TORUS_Z7 or CYCLE4.
    """
    rows = []
    bad = []
    saw_nonzero_at, saw_nonzero_below, saw_f2_only = False, False, False
    for name, N, g, gens in _synthetic_cases():
        F = _simplex_filter(N, gens, g + 2)
        gsets = [set(t) for t in gens]
        allf = defaultdict(list)
        for k in range(1, N + 1):
            for s in itertools.combinations(range(N), k):
                if not any(t <= set(s) for t in gsets):
                    allf[k].append(s)
        fb = {k: sorted(v) for k, v in allf.items()}
        row = {"case": name, "N": N, "generator_size": g, "n_generators": len(gens),
               "by_prime": {}, "ok": True}
        for p in (2, PRIMES[-1]):
            b_below, b_at, _, _ = relative_two_degrees(F, g, p)
            bdir = betti_from_faces(fb, p)
            direct = (bdir.get(g - 2, 0), bdir.get(g - 1, 0))
            agree = (b_below, b_at) == direct
            row["by_prime"][str(p)] = {"relative": [b_below, b_at], "direct": list(direct),
                                       "agree": agree}
            row["ok"] = row["ok"] and agree
            if not agree:
                bad.append("C1 %s p=%d: relative %r != direct %r"
                           % (name, p, (b_below, b_at), direct))
            if p == PRIMES[-1]:
                saw_nonzero_at = saw_nonzero_at or (b_at != 0 and agree)
                saw_nonzero_below = saw_nonzero_below or (b_below != 0 and agree)
        q = row["by_prime"][str(PRIMES[-1])]["relative"]
        f2 = row["by_prime"]["2"]["relative"]
        row["F2_sees_more_than_Q"] = f2 != q
        saw_f2_only = saw_f2_only or (row["ok"] and f2 != q)
        rows.append(row)
    report["C1_relative_vs_direct_on_known_complexes"] = rows
    report["C1_instrument_can_report_nonzero_in_target_slot"] = saw_nonzero_at
    report["C1_instrument_can_report_nonzero_one_below"] = saw_nonzero_below
    report["C1_instrument_can_see_torsion_only_F2_sees"] = saw_f2_only
    if not saw_nonzero_at:
        bad.append("C1 the instrument never reported a non-zero in the target slot")
    if not saw_nonzero_below:
        bad.append("C1 the instrument never reported a non-zero one degree below")
    if not saw_f2_only:
        bad.append("C1 the instrument never distinguished F_2 from a large prime")
    return bad


# ------------------------------------------------------------------------------------ main
def measure_c1_class(n, kmax_extra=2, verbose=True):
    """Everything about the c=1 height-1 class at this n, via the X \\ F reduction."""
    M = C1Model(n)
    d = n - 1 - 1               # needed degree n - c - 1 with c = 1
    gsize = M.m + 1             # generators have this many atoms; dimension m = n-2 = d
    F = M.filter_faces(gsize + kmax_extra)
    out = {
        "n": n, "c": 1, "m": M.m, "n_atoms": len(M.atoms),
        "needed_degree": d,
        "generator_size": gsize, "generator_dim": gsize - 1,
        "n_generators": len(M.generators()),
        "filter_faces_by_size": {str(k): len(v) for k, v in sorted(F.items())},
        "ranks_by_prime": {}, "betti_by_prime": {},
    }
    for p in PRIMES:
        # H_k(X,Gamma) with C_k(F) spanned by faces of SIZE k+1
        # beta~_{d-1}(Gamma) = H_d(X,Gamma)     = |C_d(F)| - rank(d_{d+1})
        # beta~_d(Gamma)     = H_{d+1}(X,Gamma) = (|C_{d+1}(F)| - rank(d_{d+1})) - rank(d_{d+2})
        b_below, b_at, r1, r2 = relative_two_degrees(F, gsize, p)
        out["ranks_by_prime"][str(p)] = {"d_%d" % (gsize + 1): r1, "d_%d" % (gsize + 2): r2}
        out["betti_by_prime"][str(p)] = {str(d - 1): b_below, str(d): b_at}
    vals = set(tuple(sorted(v.items())) for v in out["betti_by_prime"].values())
    out["all_primes_agree"] = len(vals) == 1
    p0 = str(PRIMES[-1])
    out["beta_needed_degree"] = out["betti_by_prime"][p0][str(d)]
    out["beta_one_below"] = out["betti_by_prime"][p0][str(d - 1)]
    # RATIONAL BOUND.  rank_{F_p} <= rank_Q always, so a mod-p Betti of 0 forces the rational
    # Betti to 0 -- one-way, and it does not need the primes to agree.  (The reverse would
    # not hold: a mod-p Betti can exceed the rational one, which is the mg-e08a trap.)
    out["rational_bound"] = {
        "argument": "rank_{F_p} <= rank_Q for every p, so beta_Q <= beta_{F_p}; a single "
                    "prime with beta_{F_p} = 0 forces beta_Q = 0",
        "beta_Q_needed_degree": 0 if out["beta_needed_degree"] == 0 else "not_forced",
        "beta_Q_one_below": 0 if out["beta_one_below"] == 0 else "not_forced",
    }
    if verbose:
        print("  n=%d c=1: m=%d atoms=%d needed degree %d; filter generated by %d faces of "
              "dim %d; beta~_%d = %s, beta~_%d = %s (primes agree: %s)"
              % (n, M.m, len(M.atoms), d, out["n_generators"], gsize - 1,
                 d, out["beta_needed_degree"], d - 1, out["beta_one_below"],
                 out["all_primes_agree"]), flush=True)
    return M, F, out


def direct_full_betti(n, verbose=True):
    """Brute force: build ALL of Gamma(P) with mg-72e4's own predicate and take its full
    reduced Betti vector.  Only affordable for small n -- this is the control that the
    X \\ F reduction and the relative route give the same answer as the thing they replace."""
    M = C1Model(n)
    faces = defaultdict(list)

    def visit(prefix):
        faces[len(prefix)].append(tuple(prefix))

    gamma_dfs(M.P, n, M.atoms, dmax=len(M.atoms), visit=visit)
    fb = {k: sorted(v) for k, v in faces.items()}
    res = {}
    for p in (2, PRIMES[-1]):        # one small prime and one large; the full complex is big
        b = betti_from_faces(fb, p)
        res[str(p)] = {str(k): v for k, v in b.items() if v}
    if verbose:
        print("  n=%d direct: %d faces, non-zero reduced Betti (p=%d): %r"
              % (n, sum(len(v) for v in fb.values()), PRIMES[-1], res[str(PRIMES[-1])]),
              flush=True)
    return {k: len(v) for k, v in sorted(fb.items())}, res


def main():
    t0 = time.time()
    report = {"ticket": "mg-bcd7", "finishes": "mg-72e4", "primes": list(PRIMES)}
    failures = []

    print("== C0: homology machinery against known answers", flush=True)
    failures += control_known_homology(report)
    print("== C1: the relative route must be able to report a NON-ZERO beta", flush=True)
    failures += control_relative_machinery(report)

    # ---------------------------------------------------------------- the class itself
    print("== the n=7 c=1 class", flush=True)
    n = 7
    M, F, main_out = measure_c1_class(n)
    report["target_class"] = main_out
    main_out["P"] = [[0, 1]]
    main_out["class_size"] = 42
    main_out["labelled_total_at_n"] = 227892

    # class size: labelled height-1 posets iso to P = ordered pairs on [7]
    if main_out["class_size"] != n * (n - 1):
        failures.append("class size %d != n(n-1) = %d" % (main_out["class_size"], n * (n - 1)))

    # ------------------------------------------------- V1: the atoms are what mg-72e4 said
    rels = set(M.rel_of_atom)
    want = set(M.A) | set(M.B) | set(M.C)
    report["V1_atom_set"] = {
        "n_atoms": len(M.atoms), "expected": 30,
        "splits_as_A_B_C": rels == want,
        "sizes": {"A_arcs_inside_V": len(M.A), "B_zero_to_V": len(M.B), "C_V_to_one": len(M.C)},
    }
    if len(M.atoms) != 30 or rels != want:
        failures.append("V1 atom set: %d atoms, split ok = %s" % (len(M.atoms), rels == want))

    # ------------------------------- V2: the direct skeleton sweep with the ORIGINAL predicate
    SKEL = int(os.environ.get("MGBCD7_SKELETON_DIM", "7"))
    print("== V2: direct skeleton sweep to dim %d with mg-72e4's own face predicate" % SKEL,
          flush=True)
    t = time.time()
    seen_ok = [True]

    def check_structural(prefix):
        # every face the ORIGINAL predicate accepts must be in X and outside F
        if not M.in_X(prefix):
            seen_ok[0] = False

    counts = gamma_dfs(M.P, n, M.atoms, dmax=SKEL, visit=check_structural)
    a = M.acyclic_profile()
    Xc = M.X_size_counts(SKEL + 1, a=a)
    Fsz = {k: len(v) for k, v in F.items()}
    pred = {d_: Xc[d_ + 1] - Fsz.get(d_ + 1, 0) for d_ in range(0, SKEL + 1)}
    report["V2_skeleton_sweep"] = {
        "dim_max": SKEL,
        "seconds": round(time.time() - t, 1),
        "measured_faces_by_dim": {str(k): v for k, v in sorted(counts.items())},
        "model_faces_by_dim": {str(k): v for k, v in sorted(pred.items())},
        "agree": counts == pred,
        "every_measured_face_lies_in_X": seen_ok[0],
        "acyclic_subset_profile_on_V": a,
        "total_faces_measured": sum(counts.values()),
        "dim7_face_count": counts.get(7),
        "mg72e4_reported_dim7_skeleton": 2075235,
        "matches_mg72e4_reported_skeleton": counts.get(7) == 2075235 if SKEL >= 7 else None,
    }
    if counts != pred:
        failures.append("V2 skeleton: measured %r != model %r" % (counts, pred))
    if not seen_ok[0]:
        failures.append("V2 a measured face is outside X")
    if SKEL >= 7 and counts.get(7) != 2075235:
        failures.append("V2 dim-7 face count %r != mg-72e4's 2075235" % counts.get(7))

    # ---------------------- V3: X is a cone, hence contractible -- checked, not just asserted
    #  every face of X of size <= SKEL+1 must stay in X after adding a fixed B-atom.
    apex = M.index_of_rel[M.B[0]]
    cone_ok = True
    for k in range(1, min(SKEL + 2, 6)):
        for S in itertools.combinations(range(len(M.atoms)), k):
            if M.in_X(S) and not M.in_X(tuple(sorted(set(S) | {apex}))):
                cone_ok = False
                break
        if not cone_ok:
            break
    report["V3_X_is_a_cone"] = {
        "apex_atom": list(M.B[0]),
        "checked_all_subsets_up_to_size": min(SKEL + 1, 5),
        "closed_under_adding_apex": cone_ok,
        "note": "X = sigma(B u C) * K_m; adding a B or C atom cannot create a cycle, so X "
                "is a cone with any B/C atom as apex, hence contractible",
    }
    if not cone_ok:
        failures.append("V3 X is not closed under adding the apex")

    # ---------------- V4: the filter is generated in exactly the needed degree, and only there
    gens = M.generators()
    minimal = all(not any(g2 < g1 for g2 in gens if g2 != g1) for g1 in gens)
    report["V4_filter"] = {
        "n_generators": len(gens), "expected": 120,
        "generator_size": M.m + 1, "generator_dim": M.m,
        "needed_degree": main_out["needed_degree"],
        "generators_are_minimal": minimal,
        "generated_in_the_needed_degree": M.m == main_out["needed_degree"],
        "filter_faces_by_size": {str(k): v for k, v in sorted(Fsz.items())},
    }
    if len(gens) != 120 or not minimal:
        failures.append("V4 filter generators: %d, minimal=%s" % (len(gens), minimal))

    # ------------- V5: relative route vs DIRECT full-complex computation at the affordable n
    print("== V5: relative route vs brute force at n = 4, 5, 6", flush=True)
    cross = {}
    for nn in (4, 5, 6):
        _, _, small = measure_c1_class(nn)
        fvec, direct = direct_full_betti(nn)
        d_ = nn - 2
        p0 = str(PRIMES[-1])
        got_direct = int(direct[p0].get(str(d_), 0))
        got_direct_below = int(direct[p0].get(str(d_ - 1), 0))
        agree = (got_direct == small["beta_needed_degree"] and
                 got_direct_below == small["beta_one_below"])
        cross[str(nn)] = {
            "direct_faces_by_size": fvec,
            "direct_nonzero_reduced_betti": direct,
            "relative_beta_needed_degree": small["beta_needed_degree"],
            "relative_beta_one_below": small["beta_one_below"],
            "direct_beta_needed_degree": got_direct,
            "direct_beta_one_below": got_direct_below,
            "agree": agree,
            "mg72e4_recorded_betti_needed": 0,
        }
        if not agree:
            failures.append("V5 n=%d: relative %r/%r vs direct %r/%r"
                            % (nn, small["beta_needed_degree"], small["beta_one_below"],
                               got_direct, got_direct_below))
    report["V5_relative_vs_direct"] = cross

    # ---------------------------- V6: negative control -- the measurement must be SENSITIVE
    #  Substitute OTHER filters, generated in the same degree and inside the same X, and the
    #  answer must move.  If every filter gives 0 then the zero above is a property of the
    #  instrument and says nothing about this class.
    #
    #  NOTE ON A WEAKER VERSION THAT WAS TRIED FIRST AND DISCARDED: dropping ONE of the 120
    #  chain-generators leaves (0, 0) as well.  That perturbation is real but not
    #  discriminating, so it is recorded here rather than used as the control.
    print("== V6: negative control -- substitute other filters generated in the same degree",
          flush=True)
    g = M.m + 1
    p = PRIMES[-1]
    truth = (main_out["beta_one_below"], main_out["beta_needed_degree"])
    perturbations = []

    def add_perturbation(name, sub_gens):
        Fp = M.filter_from(sub_gens, g + 2)
        b_below, b_at, _, _ = relative_two_degrees(Fp, g, p)
        perturbations.append({
            "filter": name, "n_generators": len(sub_gens),
            "beta_one_below": b_below, "beta_needed_degree": b_at,
            "differs_from_true_filter": (b_below, b_at) != truth,
        })

    add_perturbation("true filter minus one chain-generator", gens[1:])
    add_perturbation("a single chain-generator", gens[:1])
    add_perturbation("half the chain-generators", gens[:60])
    # size-g faces of X that are NOT chain-generators, taken deterministically
    other = []
    genset = set(tuple(sorted(t)) for t in gens)
    for S in itertools.combinations(range(len(M.atoms)), g):
        if S not in genset and M.in_X(S):
            other.append(frozenset(S))
            if len(other) >= 120:
                break
    add_perturbation("120 non-chain faces of the same size", other)
    report["V6_filter_substitutions"] = {
        "true_filter": {"beta_one_below": truth[0], "beta_needed_degree": truth[1]},
        "substitutions": perturbations,
        "at_least_one_differs": any(x["differs_from_true_filter"] for x in perturbations),
    }
    if not report["V6_filter_substitutions"]["at_least_one_differs"]:
        failures.append("V6 no substituted filter moved the answer -- the measurement is "
                        "not reading the filter")

    # ------------------------------------------------------- extension: c = 1 beyond n = 7
    EXT = int(os.environ.get("MGBCD7_EXTEND_NMAX", "9"))
    print("== extension: the c=1 class at n = 8..%d" % EXT, flush=True)
    ext = {}
    for nn in range(8, EXT + 1):
        t = time.time()
        _, _, o = measure_c1_class(nn)
        o["seconds"] = round(time.time() - t, 1)
        ext[str(nn)] = o
        if o["beta_needed_degree"] != 0:
            failures.append("extension n=%d: beta~_%d = %r" % (nn, nn - 2,
                                                               o["beta_needed_degree"]))
    report["extension_c1_beyond_n7"] = ext
    report["extension_not_attempted"] = {
        "n": 10,
        "reason": "the size-(m+3) layer of the filter is ~19M faces at n=10; not attempted, "
                  "so nothing is claimed there",
    }

    # ------- an OBSERVED pattern, recorded as a pattern and not as a proof of the c=1 case
    #  At every n measured here the two relative ranks are EXACTLY
    #      rank(d_{m+2}) = |F_{m+1}|            and     rank(d_{m+3}) = |F_{m+2}| - |F_{m+1}|,
    #  i.e. the relative complex is exact in both of the degrees read.  That is what makes
    #  both betti numbers vanish.  It holds at n = 4..EXT; it is NOT proved here, and the
    #  c=1 case therefore remains measurement, not theorem.
    pat = []
    for nn in range(4, EXT + 1):
        o = ext.get(str(nn))
        if o is None:
            _, _, o = measure_c1_class(nn, verbose=False)
        sz = {int(k): v for k, v in o["filter_faces_by_size"].items()}
        g = o["generator_size"]
        r = o["ranks_by_prime"][str(PRIMES[-1])]
        pat.append({
            "n": nn,
            "rank_d%d_equals_|F_%d|" % (g + 1, g): r["d_%d" % (g + 1)] == sz[g],
            "rank_d%d_equals_|F_%d|-|F_%d|" % (g + 2, g + 1, g):
                r["d_%d" % (g + 2)] == sz[g + 1] - sz[g],
            "filter_sizes": {str(k): v for k, v in sorted(sz.items())},
        })
    report["observed_pattern_relative_complex_is_exact"] = {
        "rows": pat,
        "holds_at_every_n_measured": all(all(v for k, v in row.items()
                                             if k.startswith("rank_")) for row in pat),
        "status": "OBSERVED at n = 4..%d, NOT PROVED.  The c=1 slice remains measurement." % EXT,
    }
    if not report["observed_pattern_relative_complex_is_exact"]["holds_at_every_n_measured"]:
        failures.append("the relative-exactness pattern does not hold at some measured n")

    # ------------------------------------------------------------------------ the headline
    report["ANSWER"] = {
        "class": "n=7, c=1, height-1, P = a single relation",
        "labelled_vertices_in_class": 42,
        "of_labelled_height1_vertices_at_n7": 227892,
        "gamma_vertices": 30,
        "needed_degree": 5,
        "beta_tilde_5_rational": main_out["beta_needed_degree"],
        "beta_tilde_4_rational": main_out["beta_one_below"],
        "coefficients": "RATIONAL reduced Betti numbers.  beta~_5(Gamma(P); Q) = 0.  This is "
                        "NOT a claim that Gamma(P) is contractible, and not a claim about "
                        "integral homology beyond the primes listed.",
        "primes": list(PRIMES),
        "torsion_note": "the F_p ranks are identical at p = 2,3,5,7 and at the large primes, "
                        "so H_5 and H_6 of the pair (X, Gamma) carry no p-torsion for those "
                        "p; nothing here rules out torsion at other primes",
        "consequence_for_mg72e4": {
            "iso_classes_measured_at_n7": "163 of 163",
            "labelled_vertices_measured_at_n7": "227892 of 227892",
            "violations": 0,
        },
    }

    report["ALL_PASS"] = not failures
    report["failures"] = failures
    report["seconds_total"] = round(time.time() - t0, 1)

    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "data", "onethird-mgbcd7-n7c1-beta5.json")
    with open(out, "w") as f:
        json.dump(report, f, indent=1, sort_keys=True)
    print()
    print("ANSWER: n=7 c=1 class -- beta~_5(Gamma(P); Q) = %s   (beta~_4 = %s)"
          % (main_out["beta_needed_degree"], main_out["beta_one_below"]))
    print("ALL_PASS =", report["ALL_PASS"], " [%ss]" % report["seconds_total"])
    for x in failures[:20]:
        print("  FAIL", x)
    print("wrote", out)
    return 0 if report["ALL_PASS"] else 1


if __name__ == "__main__":
    sys.exit(main())
