#!/usr/bin/env python3
"""
mg-56be -- INDEPENDENT AUDIT probe for mg-4f9b, on THREE axes.

mg-4f9b is generation five of a repair to
`scripts/onethird_mg2c34_n7_overlap_test.py`.  The lineage, because it is why
the bar is high and every generation looked like a fix to its author:

    mg-09ea  AUDIT     two controls passing while blind        CAUGHT
    mg-60d3  gate fix  repaired those two instances            class survived
    mg-5ad1  AUDIT     one-character selector flip passes      CAUGHT
    mg-75f0  gate fix  widened 4 fields -> the whole row       class survived
    mg-bd53  AUDIT     a REGRESSION, and the class still open  CAUGHT
    mg-4f9b  gate fix  restored the route axis; named a THIRD  <- audited here

mg-4f9b's headline is not a widening.  It is a NEGATIVE: it claims the gate
CANNOT close the one-character-selector class, because the identity reference is
a frozen snapshot of the same code path the gate is checking, so a mutation
shipped together with a regenerated dataset is invisible to any number of
comparisons against that reference.  It recorded that in the gate's own header
under WHAT THIS GATE CANNOT SEE and asked, in as many words, that the negative
be attacked rather than believed: "A 'no' is a comfortable thing for an author
to write because nothing can then be shown to have failed."

This file is that attack, plus the two coverage axes the brief also requires.

=============================================================================
WHAT IS HERE, AND WHAT EACH PART SETTLES
=============================================================================
PART 1  THE PROVENANCE INSTRUMENT, and it is mechanical rather than declared.
        mg-4f9b's third axis asks, per control, whether its reference is a
        THEOREM the corpus cannot produce or a STORED NUMBER the corpus
        produced and committed.  A hand-authored table answering that is a
        claim; this measures it.  Perturb the committed dataset -- every float
        field scaled by (1 + 1e-6) -- and run the gate.  A control whose
        verdict MOVES when the store moves has a stored reference.  A control
        whose verdict is INVARIANT does not.  One gate run partitions all of
        them, with no appeal to anybody's docstring.

PART 2  MUTATE AND REGENERATE, seven runs.  For each of C2 / M3 / M4 (and
        mg-56be-A below), run the mutation ALONE and then the mutation with the
        eight rows the gate reads REGENERATED by the mutated code -- edit,
        re-run, commit, which is what an author does and not an attack.  This
        is mg-4f9b's own experiment, rebuilt from scratch, because a control
        validated only by re-running the author's instrument is the failure
        mode this lineage keeps reproducing.  mg-4f9b's probe is at
        `scripts/onethird_mg4f9b_route_axis_probe.py` part 3 and asks not to be
        the thing an auditor runs.  It is not run here.

PART 3  THE CONSTRUCTIVE REFUTATION -- the part that settles mg-4f9b's
        negative.  It asks the adversarial question mg-4f9b named as primary:
        does a cheap reference INDEPENDENT OF THE CORPUS exist for
        `frozen_pair_overlap_with_U`?  mg-4f9b considered exactly one candidate
        -- having the gate read its own committed output back -- rejected it
        correctly (that relocates the mutation into the row above), and
        generalised from that single rejection to "no".

        FIVE candidates are exhibited and measured here.  Three of them fire on
        mutations the gate absorbs, and they fire UNDER REGENERATION, because
        their references are 0, 1 and an inequality -- there is no stored number
        to regenerate.  See THE FIVE INVARIANTS below.

PART 4  MY OWN MUTATIONS, in fields and routes neither mg-75f0, mg-bd53 nor
        mg-4f9b used, plus one that turned out to be a no-op and is reported as
        such because "I tried this and it did nothing" is data.

=============================================================================
THE FIVE INVARIANTS (part 3), and why each is provenance-independent
=============================================================================
Let P be a measured poset, (x, y) the Theorem-E frozen pair, f the vector
`gate.frozen_pair_indicator(P, x, y)` over L(P), and P_U the projector onto
U = span{sigma |-> 1[sigma(a) = i]} built by `mg4a86.projector_U`.  The gate
reports `frozen_pair_overlap_with_U` = f^T P_U f and NEVER READS IT BACK, which
is mg-bd53 finding 2: one line dropped from `frozen_pair_indicator` moves it
0.807 -> 0.904, printed, exit 0, on all four gate generations.

  I1  CENTRING.        sum_sigma f(sigma) = 0.
      Reference: the integer 0, from "a mean-centred vector sums to zero".
      MEASURED: baseline |sum f| <= 2.3e-16; under mg-bd53's C2 it is 8.1 to
      13.5.  Fires by twelve orders of magnitude on the mutation that has
      survived four generations.

  I2  NORMALISATION.   ||f|| = 1.
      Reference: the integer 1, from "the function returns f/||f||".
      Catches the sibling mutation (drop the division) that C2 does not.

  I3  PROJECTOR RANGE. 0 <= f^T P_U f <= ||f||^2.
      Reference: the closed interval [0, 1], from "P_U is an orthogonal
      projector and f is a unit vector".  Cheap; catches gross corruption of
      the projector only, and is reported as the weak one that it is.

  I4  BESSEL, WITH AN EXPLICIT WITNESS -- the one that is a real theorem about
      this specific quantity rather than about floating point hygiene.
      g(sigma) = pos_sigma(y) - pos_sigma(x) is a LINEAR COMBINATION OF THE
      POSITION INDICATORS, g = sum_a a * (e_{y,a} - e_{x,a}), so g lies in U by
      construction -- verified here, not assumed: ||P_U ghat - ghat|| <= 5.1e-15
      at every measured poset.  Bessel then gives
              f^T P_U f  >=  <f, ghat>^2                        for unit ghat.
      Reference: an inequality with a constructible witness.  The corpus cannot
      regenerate an inequality.
      MEASURED, and this is why it is worth having: the bound is TIGHT.
      0.7881 against 0.8072, 0.7876 against 0.8094, 0.7878 against 0.8097 --
      the frozen-pair indicator is within 2.4% of being explained by a single
      rank-difference observable.  That is a fact about the corpus's own
      mechanism claim, obtained from a control.

  I5  A SECOND ROUTE FOR THE VALUE (route axis, not provenance).  f^T P_U f
      recomputed by least squares against the |L| x n^2 position-indicator
      matrix, which never forms the SVD projector and never touches its rank
      filter.  Agrees to 1.1e-15.  This is what CONTROL E's rank filter (M4)
      would have to move both of.

  I6  THE VACUITY FLOOR, and it is the same species of check CONTROL E already
      applies to dim U.  `_projector_row_ok` requires dim_U < |L| because if U
      is the whole space then c == 1 identically and sec 2's own `null`
      criterion says the measurement carries no signal.  The identical argument
      applies one level down: if f^T P_U f = 1 then the degree-2 pair indicator
      lies ENTIRELY inside the degree-1 position space, and the corpus's
      inference ("degree-2 slow mode => c ~ 0") is being read off a quantity
      that has gone vacuous.
      MEASURED: mg-5ad1's M3 selector flip drives it to 1.000000 at 3 of 3
      off-regime posets (1 - ov = 2.2e-15, -2.9e-15, 0.0).  A floor at
      1 - 1e-6 fires on M3 WITH THE DATASET REGENERATED, which is the case
      mg-4f9b measured as exit 0 everywhere.
      SCOPE, stated because a control whose stated reason is wider than its
      real one is this arc's named defect: the floor is a statement about the
      OFF-REGIME MEASURED POSETS, where the corpus's own claim is that the
      overlap is ~0.81.  There are posets where f in U legitimately.  The fix
      if it ever fires legitimately is to narrow the population, not to loosen
      the number.

WHAT THIS DOES AND DOES NOT SETTLE.  mg-4f9b's DIAGNOSIS is correct and is the
most valuable thing in the arc: no amount of comparing against the stored
reference closes the class, because a mutation can move the comparison and its
reference together.  Every invariant above works precisely BECAUSE it is not
such a comparison.  mg-4f9b's CONCLUSION -- that the class is therefore not the
gate's to close and belongs to the independent audit stage -- does not follow,
and is refuted by construction: I1 and I6 are together about fifteen lines,
cost nothing, and close mg-bd53's C2 and mg-5ad1's M3-under-regeneration, which
are the two open instances the header names.

=============================================================================
Run:  /usr/bin/python3 scripts/onethird_mg56be_provenance_audit.py
      (numpy required; ~10 min -- twelve full runs of the CI gate)
      --part3-only    the invariants alone, no gate runs, ~40 s
      --only C2,M3    run a subset of part 2 / part 4
Writes `data/onethird-mg56be-provenance-audit.json`.
"""

import os
import sys
import json
import copy
import shutil
import hashlib
import argparse
import tempfile
import subprocess

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(REPO, "scripts")
GATE = os.path.join("scripts", "onethird_mg2c34_n7_overlap_test.py")
DATASET = "onethird-mg8b64-L1b-bk-transport-transfer.json"

MG4A86_OV = "scripts/onethird_mg4a86_sdquant_overlap.py"
MG4A86_SD = "scripts/onethird_mg4a86_standard_dominance_target_audit.py"
MG8B64 = "scripts/onethird_mg8b64_L1b_bk_transport_transfer_probe.py"

# Thread pinning, for the same reason mg-bd53 pins: the compared float fields
# reproduce to 0.00e+00 uncontended and to ~1e-15 single-threaded, six orders
# under the gate's 1e-9 tolerance either way -- but unpinned threads move the
# printed digits run to run, and "the mutation moved nothing" is measured here
# by comparing printed output.
PINNED = {"OMP_NUM_THREADS": "1", "OPENBLAS_NUM_THREADS": "1",
          "MKL_NUM_THREADS": "1", "VECLIB_MAXIMUM_THREADS": "1",
          "NUMEXPR_NUM_THREADS": "1"}


# ---------------------------------------------------------------- mutations --
# Anchors carry an occurrence COUNT and it is asserted before the edit.  A
# mutation whose anchor has drifted is a NO-OP, and a no-op run reported as a
# pass is a lie -- mg-75f0 shipped exactly that defect and mg-bd53 found it.
MUTATIONS = {
    # ---- reproduced from mg-bd53, to check its matrix rather than cite it ----
    "C2": {
        "desc": "the gate's own frozen_pair_indicator loses its centring "
                "(mg-bd53 C2).  Moves frozen_pair_overlap_with_U -- the "
                "quantity ledger claim 8 rests on -- 0.807 -> 0.904, and three "
                "sibling quantities with it",
        "file": GATE,
        "old": "    f -= f.mean()\n",
        "new": "    f -= 0.0 * f.mean()\n",
        "count": 1,
        "regenerable": False,
        "why_not_regenerable": "the quantity lives in the gate's OWN output "
                               "file, which the gate never reads back, so "
                               "there is no stored reference to regenerate "
                               "and the mutation is absorbed with or without "
                               "one",
    },
    "M3": {
        "desc": "mg-8b64's Theorem-E frozen-pair selector min -> max "
                "(mg-5ad1 M3).  The one-character flip the whole lineage is "
                "about",
        "file": MG8B64,
        "old": '    frozen = min((pc for pc in pairs if pc["ratio"] is not '
               'None),\n                 key=lambda pc: pc["ratio"], '
               'default=None)',
        "new": '    frozen = max((pc for pc in pairs if pc["ratio"] is not '
               'None),\n                 key=lambda pc: pc["ratio"], '
               'default=None)',
        "count": 1,
        "regenerable": True,
    },
    "M4": {
        "desc": "projector_U's rank filter s > max(tol,1e-10) -> s > 0.0 "
                "(mg-5ad1 M4).  CONTROL E's case: a theorem reference, so "
                "regeneration must NOT save it",
        "file": MG4A86_OV,
        "old": "    Q = Uu[:, s > max(tol, 1e-10)]",
        "new": "    Q = Uu[:, s > 0.0]",
        "count": 1,
        "regenerable": True,
    },
    # ------------------------------- mine, part 4 ---------------------------
    "mg56be-A": {
        "desc": "MINE.  BK_CHEEGER_CAP 15 -> 6 in mg-8b64.  h_bk_exhaustive "
                "and h_bk_argmin_is_pair_cut stop existing on 36 of the 47 "
                "reconstructible rows that carry them -- and NOT on the ONE "
                "poset the gate compares them at, because that poset has "
                "|L| = 6.  Aimed squarely at the per-dataset census mg-4f9b "
                "added: the census is a FIELD-NAME statement being read as a "
                "coverage statement",
        "file": MG8B64,
        "old": "BK_CHEEGER_CAP = 15",
        "new": "BK_CHEEGER_CAP = 6",
        "count": 1,
        "regenerable": True,
    },
    "mg56be-B": {
        "desc": "MINE, ROUTE AXIS.  Unwire lambda_std's restored second route "
                "in the gate and leave IDENTITY_SECOND_ROUTES declaring TWO "
                "ROUTES.  This is mg-75f0's regression re-committed one level "
                "up: the declaration is a gate condition, the WIRING is not",
        "file": GATE,
        "old": '            rec["match_lambda_std"] = bool(rec["match_lambda_std"]\n'
               '                                           and rec["second_route_lambda_std_ok"])',
        "new": '            rec["match_lambda_std"] = bool(rec["match_lambda_std"])',
        "count": 1,
        "regenerable": False,
        "why_not_regenerable": "the mutation is in the gate, not in a corpus "
                               "quantity; regeneration is not the axis it "
                               "tests",
    },
    "mg56be-B+B1": {
        "desc": "MINE.  mg56be-B together with mg-bd53's B1 (mg-4a86's own "
                "lambda_std, np.max -> np.min).  The decisive one: if this "
                "exits 0 then the REGRESSION mg-4f9b was created to repair is "
                "reinstated by a two-line edit that every gate condition in "
                "the file passes, IDENTITY_SECOND_ROUTES still says TWO "
                "ROUTES, and _identity_routes_declared() still returns clean",
        "file": None,          # composite, applied as two edits
        "composite": ["mg56be-B", "B1"],
        "count": None,
        "regenerable": False,
    },
    "B1": {
        "desc": "mg-bd53 B1, mg-4a86's own lambda_std np.max(w) -> np.min(w).  "
                "THE REGRESSION mg-4f9b repaired; here as the second half of "
                "the composite above",
        "file": MG4A86_SD,
        "old": "    return float(np.max(w))",
        "new": "    return float(np.min(w))",
        "count": 1,
        "regenerable": True,
    },
}

# Part 2/4 plan: (case name, mutation key, regenerate?)
PLAN = [
    ("none",              None,           False),
    ("C2",                "C2",           False),
    ("C2+regen",          "C2",           True),
    ("M3",                "M3",           False),
    ("M3+regen",          "M3",           True),
    ("M4",                "M4",           False),
    ("M4+regen",          "M4",           True),
    ("mg56be-A",          "mg56be-A",     False),
    ("mg56be-A+regen",    "mg56be-A",     True),
    ("mg56be-B",          "mg56be-B",     False),
    ("mg56be-B+B1",       "mg56be-B+B1",  False),
]

# What the audit EXPECTS, so a row that changes is visible rather than absorbed
# into a narrative.  `None` means "not predicted -- this run is the measurement".
EXPECTED = {
    "none": 0,
    "C2": 0,             # mg-bd53 finding 2, mg-4f9b states it is not closed
    "C2+regen": 0,
    "M3": 1,             # target 2 of the brief: the flip must still be caught
    "M3+regen": 0,       # mg-4f9b's provenance claim, tested not cited
    "M4": 1,
    "M4+regen": 1,       # a THEOREM reference: regeneration must not save it
    "mg56be-A": None,
    "mg56be-A+regen": None,
    "mg56be-B": None,
    "mg56be-B+B1": None,
}


# ------------------------------------------------------------- tree building --
def _apply_one(root, key):
    mu = MUTATIONS[key]
    path = os.path.join(root, mu["file"])
    with open(path) as f:
        src = f.read()
    got = src.count(mu["old"])
    if got != mu["count"]:
        raise SystemExit(
            f"{key}: anchor found {got} times in {mu['file']}, expected "
            f"{mu['count']} -- the mutation would be a NO-OP and the run "
            f"would be a lie.  Anchor:\n{mu['old']}")
    with open(path, "w") as f:
        f.write(src.replace(mu["old"], mu["new"]))
    return {"file": mu["file"], "occurrences": got}


def build_tree(root, mutation):
    os.makedirs(os.path.join(root, "scripts"))
    os.makedirs(os.path.join(root, "data"))
    for fn in os.listdir(SCRIPTS):
        if fn.endswith(".py"):
            shutil.copy2(os.path.join(SCRIPTS, fn),
                         os.path.join(root, "scripts", fn))
    shutil.copy2(os.path.join(REPO, "data", DATASET),
                 os.path.join(root, "data", DATASET))
    if mutation is None:
        return []
    mu = MUTATIONS[mutation]
    keys = mu.get("composite") or [mutation]
    return [_apply_one(root, k) for k in keys]


# ------------------------------------------------------------- regeneration --
# THE POINT OF THIS FUNCTION.  It is what an author does: edit a probe, re-run
# it, commit the numbers it now produces.  No adversarial intent is needed and
# none is modelled.  It regenerates ONLY the eight rows the gate's identity
# population reads, which is strictly LESS than a real re-run of mg-8b64's probe
# would touch -- so any mutation this does not save would also not be saved by a
# full regeneration, and the measurement is conservative in the direction that
# favours the gate.
REGEN_SNIPPET = r'''
import sys, json
sys.path.insert(0, "scripts")
import onethird_mg2c34_n7_overlap_test as gate
from onethird_mgb0a6_spectral_killshot_probe import enumerate_both_connected
from onethird_mg8b64_L1b_bk_transport_transfer_probe import (
    analyze_poset, biased_families)

Ps = enumerate_both_connected(7)
targets = {}
for i in gate.OFF_REGIME + gate.IN_REGIME + gate.DEGENERATE_LAMBDA2:
    targets["enum-n7-#%d" % i] = Ps[i]
# The small-|L| poset mg-4f9b added.  `IDENTITY_SMALL_L_POSET` is a LOCAL of the
# gate's main(), not a module attribute, so it cannot be read off the module --
# the name is spelled out here and the count is asserted by the caller against
# the number of identity rows the gate actually printed.  The first version of
# this file read it off the module, raised AttributeError inside the subprocess,
# and the caller SWALLOWED the failure: every "+regen" case then ran with an
# unregenerated dataset and reproduced the mutation-alone exit code exactly.
# That is a provenance experiment silently degrading into a repeat of the run it
# is supposed to be compared against, which is worth the paragraph.
SMALL_L = "N (2+2)"
targets["fam:" + SMALL_L] = biased_families()[SMALL_L]

path = "data/__DATASET__"
with open(path) as f:
    doc = json.load(f)
by_name = {r["name"]: k for k, r in enumerate(doc["rows"])}
regenerated = []
for name, P in targets.items():
    if name not in by_name:
        continue
    doc["rows"][by_name[name]] = analyze_poset(P, name)
    regenerated.append(name)
with open(path, "w") as f:
    json.dump(doc, f, indent=1)
print("REGENERATED " + ",".join(sorted(regenerated)))
'''.replace("__DATASET__", DATASET)


# The number of rows a regeneration MUST rewrite.  Asserted, not hoped for: a
# regeneration that silently rewrites nothing makes a "+regen" run
# indistinguishable from the mutation-alone run it is being compared against,
# and the comparison is the entire experiment.
REGEN_EXPECTED_ROWS = 8


def regenerate(root):
    """Re-run the mutated row builder over the identity population and commit
    what it now produces, into this tree's copy of the dataset.

    FAILS LOUDLY.  A silent no-op here would report "the mutation is still
    caught under regeneration" while no regeneration happened -- which would be
    a false NEGATIVE against mg-4f9b's central measurement, and this file exists
    to test that measurement rather than to manufacture a disagreement with it."""
    proc = subprocess.run(["/usr/bin/python3", "-c", REGEN_SNIPPET],
                          cwd=root, capture_output=True, text=True,
                          env=dict(os.environ, **PINNED))
    if proc.returncode != 0:
        raise SystemExit(f"REGENERATION FAILED, and a swallowed failure here "
                         f"invalidates every '+regen' row:\n"
                         f"{proc.stderr[-3000:]}")
    names = [ln for ln in proc.stdout.splitlines()
             if ln.startswith("REGENERATED ")]
    rows = names[0].split(" ", 1)[1].split(",") if names else []
    if len(rows) != REGEN_EXPECTED_ROWS:
        raise SystemExit(
            f"REGENERATION rewrote {len(rows)} rows, expected "
            f"{REGEN_EXPECTED_ROWS} ({sorted(rows)}).  The identity population "
            f"has changed, or a name no longer resolves -- either way the "
            f"'+regen' rows would be measuring the wrong thing")
    return {"ok": True, "rows": rows}


def extract(stdout):
    fails, ident, census = [], [], []
    grab = False
    for line in stdout.splitlines():
        if line.startswith("CONTROL FAILURES:"):
            grab = True
            continue
        if grab and line.strip().startswith("- "):
            fails.append(line.strip()[2:])
        if "mismatched:" in line or "fields compared" in line:
            ident.append(line.strip())
        if "CENSUS OVER THE DATASET" in line:
            census.append(line.strip())
    return fails, ident, census


def run_case(case, mutation, regen):
    root = tempfile.mkdtemp(prefix=f"mg56be-{case}-")
    try:
        applied = build_tree(root, mutation)
        rinfo = regenerate(root) if regen else None
        proc = subprocess.run(["/usr/bin/python3", GATE, "--no-sweep"],
                              cwd=root, capture_output=True, text=True,
                              env=dict(os.environ, **PINNED))
        fails, ident, census = extract(proc.stdout)
        return {"case": case, "mutation": mutation, "regenerated": rinfo,
                "applied": applied, "exit": proc.returncode,
                "gate_failures": fails, "identity_lines": ident,
                "census_lines": census,
                "stdout_sha256": hashlib.sha256(
                    proc.stdout.encode()).hexdigest(),
                "stderr_tail": (proc.stderr[-2000:] if proc.returncode > 1
                                else "")}
    finally:
        shutil.rmtree(root, ignore_errors=True)


# ================================================================== part 1 ===
def part1_provenance():
    """MECHANICAL provenance partition: perturb the store, see whose verdict
    moves.

    A control with a STORED reference decides by comparing against a number the
    corpus committed, so scaling that number changes its verdict.  A control
    with a THEOREM reference decides against a closed form and cannot notice.
    One gate run, and it appeals to nobody's docstring."""
    print("=" * 78)
    print("PART 1 -- PROVENANCE, MEASURED: perturb the store, see who notices")
    print("=" * 78)
    root = tempfile.mkdtemp(prefix="mg56be-provenance-")
    try:
        build_tree(root, None)
        path = os.path.join(root, "data", DATASET)
        with open(path) as f:
            doc = json.load(f)
        touched = 0
        for row in doc["rows"]:
            for k, v in list(row.items()):
                if isinstance(v, float) and v == v and v != 0.0:
                    row[k] = v * (1.0 + 1e-6)
                    touched += 1
        with open(path, "w") as f:
            json.dump(doc, f, indent=1)
        proc = subprocess.run(["/usr/bin/python3", GATE, "--no-sweep"],
                              cwd=root, capture_output=True, text=True,
                              env=dict(os.environ, **PINNED))
        fails, _, _ = extract(proc.stdout)
    finally:
        shutil.rmtree(root, ignore_errors=True)

    # Which named controls appear in the failure list?
    def hit(tag):
        return any(tag in f for f in fails)

    controls = [
        ("CONTROL A  graded analytic, c = cos^2(theta)",
         "CONTROL A", "THEOREM"),
        ("CONTROL B  antichain c = 1, dim U = (n-1)^2+1",
         "CONTROL B", "THEOREM"),
        ("CONTROL C  broken projector must NOT return 1",
         "CONTROL C", "THEOREM"),
        ("CONTROL E  dim U <= (n-1)^2+1 and dim U < |L|",
         "CONTROL E", "THEOREM"),
        ("CONTROL F  two-sided reading-dependence on real data",
         "CONTROL F", "THEOREM"),
        ("IDENTITY   recomputed row vs the committed row",
         "committed mg-8b64 row", "STORED"),
    ]
    print(f"  perturbed {touched} float values in the committed dataset by "
          f"a relative 1e-6\n")
    print(f"  {'control':<48} {'verdict moved':>13}  {'reference':>9}")
    ledger = []
    disagree = []
    for label, tag, declared in controls:
        moved = hit(tag)
        measured = "STORED" if moved else "THEOREM"
        print(f"  {label:<48} {str(moved):>13}  {measured:>9}")
        ledger.append({"control": label, "verdict_moved_when_store_moved":
                       moved, "reference_measured": measured,
                       "reference_declared": declared})
        if measured != declared:
            disagree.append(f"{label}: gate header implies {declared}, "
                            f"measurement says {measured}")
    stored = [c["control"] for c in ledger
              if c["reference_measured"] == "STORED"]
    theorem = [c["control"] for c in ledger
               if c["reference_measured"] == "THEOREM"]
    print()
    print(f"  STORED-reference controls  ({len(stored)}): coverage from these "
          f"is an UPPER BOUND, not")
    print(f"     a durable number -- it holds only until somebody re-runs the "
          f"probe that")
    print(f"     wrote the store.  {', '.join(s.split()[0] + ' ' + s.split()[1] for s in stored)}")
    print(f"  THEOREM-reference controls ({len(theorem)}): survive "
          f"regeneration by construction.")
    return {"floats_perturbed": touched, "gate_exit_on_perturbed_store":
            proc.returncode, "ledger": ledger,
            "stored_reference_controls": stored,
            "theorem_reference_controls": theorem}, disagree


# ================================================================== part 3 ===
def part3_invariants():
    """THE CONSTRUCTIVE REFUTATION.  Does a corpus-independent reference exist
    for `frozen_pair_overlap_with_U`?  Five candidates, measured, at baseline
    and under the two mutations the gate absorbs."""
    sys.path.insert(0, SCRIPTS)
    import onethird_mg2c34_n7_overlap_test as gate
    from onethird_mgb0a6_spectral_killshot_probe import enumerate_both_connected
    from onethird_mg4a86_sector_leakage_and_tempering import one_particle_span
    from onethird_mg4a86_sdquant_overlap import projector_U
    import onethird_mg8b64_L1b_bk_transport_transfer_probe as mg8b64

    print()
    print("=" * 78)
    print("PART 3 -- IS THERE A CORPUS-INDEPENDENT REFERENCE FOR")
    print("          frozen_pair_overlap_with_U?  (mg-4f9b says no)")
    print("=" * 78)

    def uncentred(P, x, y):
        """mg-bd53's C2, as a function rather than a source edit, so the
        invariants can be evaluated on both variants in one process."""
        les = P.linear_extensions()
        f = np.zeros(len(les))
        for r, perm in enumerate(les):
            pos = {e: i for i, e in enumerate(perm)}
            f[r] = 1.0 if pos[x] < pos[y] else 0.0
        f -= 0.0 * f.mean()
        nrm = np.linalg.norm(f)
        return f / nrm if nrm > 0 else f

    def evaluate(P, x, y, indicator):
        les = P.linear_extensions()
        m, n = len(les), P.n
        PU, dim_U = projector_U(P)
        f = indicator(P, x, y)
        ov = float(f @ (PU @ f))
        M = one_particle_span(P)
        # I4's witness: g = pos(y) - pos(x) = sum_a a (e_{y,a} - e_{x,a}) in U
        g = np.zeros(m)
        for a in range(n):
            g += a * (M[:, y * n + a] - M[:, x * n + a])
        g = g - g.mean()
        ng = float(np.linalg.norm(g))
        gh = g / ng if ng > 0 else g
        witness_in_U = float(np.linalg.norm(PU @ gh - gh))
        bessel = float((f @ gh) ** 2)
        coef, *_ = np.linalg.lstsq(M, f, rcond=None)
        lsq = float(np.dot(M @ coef, M @ coef))
        return {
            "overlap": ov, "dim_U": int(dim_U), "num_LE": m,
            "I1_abs_sum_f": float(abs(f.sum())),
            "I2_norm_defect": float(abs(np.linalg.norm(f) - 1.0)),
            "I3_in_range": bool(-1e-12 <= ov <= 1.0 + 1e-12),
            "I4_witness_in_U_defect": witness_in_U,
            "I4_bessel_lower_bound": bessel,
            "I4_bound_holds": bool(bessel <= ov + 1e-9),
            "I4_tightness": (bessel / ov) if ov > 0 else None,
            "I5_lstsq_overlap": lsq,
            "I5_route_defect": float(abs(lsq - ov)),
            "I6_vacuity_margin": float(1.0 - ov),
        }

    TOL = {"I1": 1e-9, "I2": 1e-9, "I4_in_U": 1e-9, "I5": 1e-6,
           "I6_floor": 1e-6}

    def verdicts(e):
        return {
            "I1_centring": e["I1_abs_sum_f"] <= TOL["I1"],
            "I2_normalised": e["I2_norm_defect"] <= TOL["I2"],
            "I3_in_range": e["I3_in_range"],
            "I4_bessel": (e["I4_witness_in_U_defect"] <= TOL["I4_in_U"]
                          and e["I4_bound_holds"]),
            "I5_second_route": e["I5_route_defect"] <= TOL["I5"],
            "I6_not_vacuous": e["I6_vacuity_margin"] > TOL["I6_floor"],
        }

    Ps = enumerate_both_connected(7)
    out = {"tolerances": TOL, "posets": []}
    print()
    print("  BASELINE, and the reference each invariant compares against:")
    print(f"  {'poset':>14} {'overlap':>9} {'I1 |sum f|':>11} "
          f"{'I2 |‖f‖-1|':>11} {'I4 bound':>9} {'tight':>7} "
          f"{'I5 |diff|':>10} {'I6 1-ov':>10}")
    for i in gate.OFF_REGIME:
        name = f"enum-n7-#{i}"
        P = Ps[i]
        pairs = mg8b64.bk_frozen_pair(P)["pairs"]
        fr_min = min((pc for pc in pairs if pc["ratio"] is not None),
                     key=lambda pc: pc["ratio"])
        fr_max = max((pc for pc in pairs if pc["ratio"] is not None),
                     key=lambda pc: pc["ratio"])
        base = evaluate(P, fr_min["x"], fr_min["y"],
                        gate.frozen_pair_indicator)
        c2 = evaluate(P, fr_min["x"], fr_min["y"], uncentred)
        m3 = evaluate(P, fr_max["x"], fr_max["y"],
                      gate.frozen_pair_indicator)
        rec = {"name": name,
               "frozen_pair_min_ratio": [int(fr_min["x"]), int(fr_min["y"])],
               "frozen_pair_max_ratio": [int(fr_max["x"]), int(fr_max["y"])],
               "baseline": base, "baseline_verdicts": verdicts(base),
               "C2_uncentred": c2, "C2_verdicts": verdicts(c2),
               "M3_maxratio_pair": m3, "M3_verdicts": verdicts(m3)}
        out["posets"].append(rec)
        print(f"  {name:>14} {base['overlap']:>9.6f} "
              f"{base['I1_abs_sum_f']:>11.2e} {base['I2_norm_defect']:>11.2e} "
              f"{base['I4_bessel_lower_bound']:>9.6f} "
              f"{base['I4_tightness']:>7.4f} {base['I5_route_defect']:>10.2e} "
              f"{base['I6_vacuity_margin']:>10.2e}")

    print()
    print("  DO THEY FIRE ON WHAT THE GATE ABSORBS?  (False = the invariant "
          "is violated,")
    print("  i.e. the mutation is CAUGHT.  Every reference below is 0, 1 or an "
          "inequality,")
    print("  so REGENERATION CANNOT MOVE IT -- there is no stored number.)")
    print()
    keys = ["I1_centring", "I2_normalised", "I3_in_range", "I4_bessel",
            "I5_second_route", "I6_not_vacuous"]
    print(f"  {'variant':<34} " + " ".join(f"{k.split('_')[0]:>5}" for k in keys)
          + "   CAUGHT BY")
    failures = []
    for rec in out["posets"]:
        for tag, vk in (("baseline", "baseline_verdicts"),
                        ("C2 (uncentred)", "C2_verdicts"),
                        ("M3 (max-ratio pair)", "M3_verdicts")):
            v = rec[vk]
            caught = [k.split("_")[0] for k in keys if not v[k]]
            print(f"  {rec['name'] + '  ' + tag:<34} "
                  + " ".join(f"{'ok' if v[k] else 'FIRE':>5}" for k in keys)
                  + f"   {','.join(caught) if caught else '-- nothing'}")
    print()
    # The audit's own assertions: these are what make this file a control.
    for rec in out["posets"]:
        nm = rec["name"]
        if not all(rec["baseline_verdicts"].values()):
            failures.append(
                f"PART 3: {nm}: an invariant FIRES ON THE UNMUTATED TREE "
                f"({[k for k, v in rec['baseline_verdicts'].items() if not v]})"
                f" -- the invariant is wrong, not the corpus")
        if rec["C2_verdicts"]["I1_centring"]:
            failures.append(
                f"PART 3: {nm}: I1 does NOT fire on C2.  The constructive "
                f"refutation of mg-4f9b's negative rests on it")
        if rec["M3_verdicts"]["I6_not_vacuous"]:
            failures.append(
                f"PART 3: {nm}: I6 does NOT fire on M3 (1 - overlap = "
                f"{rec['M3_maxratio_pair']['I6_vacuity_margin']:.2e}) -- M3 "
                f"under regeneration stays open")
    c2_caught = all(not r["C2_verdicts"]["I1_centring"] for r in out["posets"])
    m3_caught = all(not r["M3_verdicts"]["I6_not_vacuous"]
                    for r in out["posets"])
    print(f"  VERDICT ON mg-4f9b's NEGATIVE ('the gate cannot close this "
          f"class'):")
    print(f"    C2, the open instance mg-bd53 found  -- closed by I1 at 3/3 "
          f"posets: {c2_caught}")
    print(f"    M3 under regeneration                -- closed by I6 at 3/3 "
          f"posets: {m3_caught}")
    print(f"    Both references are corpus-independent, so both survive "
          f"regeneration.")
    print(f"    mg-4f9b's DIAGNOSIS (no comparison against the stored "
          f"reference can close")
    print(f"    the class) is CORRECT.  Its CONCLUSION (therefore the gate "
          f"cannot) does not")
    print(f"    follow: neither invariant is such a comparison.")
    out["refutation"] = {"C2_closed_by_I1": c2_caught,
                         "M3_closed_by_I6": m3_caught}
    return out, failures


# ================================================================== part 4 ===
def part4_route_declaration_vs_wiring():
    """Is the RESTORED route enforced, or only DECLARED?

    mg-4f9b made the declaration a gate condition (`_identity_routes_declared`)
    and said in the gate's own comment that the WIRING is checked only by its
    own probe, which is not in CI.  It justified that by the cost of verifying
    the two implementations are still DISTINCT -- which does need three imports
    and a source diff.  Verifying a declared route is WIRED AT ALL does not: it
    is a key-presence check on the record the identity loop already builds.
    This part measures the gap that conflation leaves open, and part 2's
    mg56be-B / mg56be-B+B1 rows are the gate runs that settle it."""
    sys.path.insert(0, SCRIPTS)
    import onethird_mg2c34_n7_overlap_test as gate
    print()
    print("=" * 78)
    print("PART 4 -- the route axis: DECLARED, or WIRED?")
    print("=" * 78)
    declared = {f: (d["second_route"] is not None)
                for f, d in gate.IDENTITY_SECOND_ROUTES.items()}
    src = open(os.path.join(REPO, GATE)).read()
    wired = {f: (f'rec["second_route_{f}_ok"]' in src) for f in declared}
    anded = {f: (f'and rec["second_route_{f}_ok"]' in src) for f in declared}
    print(f"  {'quantity':<12} {'declares 2nd route':>19} "
          f"{'computes it':>12} {'ANDs it in':>11}")
    problems = []
    for f in sorted(declared):
        print(f"  {f:<12} {str(declared[f]):>19} {str(wired[f]):>12} "
              f"{str(anded[f]):>11}")
        if declared[f] and not (wired[f] and anded[f]):
            problems.append(f"PART 4: {f} DECLARES a second route that is not "
                            f"wired into field_matches")
    print()
    print("  `_identity_routes_declared()` is a gate condition and checks the "
          "LEFT column.")
    print("  Nothing in the gate checks the two right-hand columns.  A "
          "three-line")
    print("  key-presence assertion over IDENTITY_SECOND_ROUTES would, and "
          "would have")
    print("  turned mg-75f0's silent route drop into a gate failure.")
    return {"declared": declared, "computes": wired, "ands_into_matches": anded,
            "declaration_is_a_gate_condition": True,
            "wiring_is_a_gate_condition": False}, problems


# ==================================================================== main ===
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--part3-only", action="store_true",
                    help="the invariants and the route table; no gate runs")
    ap.add_argument("--only", default="",
                    help="comma-separated subset of part 2/4 case names")
    args = ap.parse_args()

    report = {"work_item": "mg-56be", "audits": "mg-4f9b",
              "gate": GATE, "dataset": DATASET}
    failures = []

    inv, f3 = part3_invariants()
    report["part3_invariants"] = inv
    failures += f3
    route, f4 = part4_route_declaration_vs_wiring()
    report["part4_route_declaration_vs_wiring"] = route
    failures += f4

    if not args.part3_only:
        prov, f1 = part1_provenance()
        report["part1_provenance"] = prov
        failures += f1

        want = [c.strip() for c in args.only.split(",") if c.strip()]
        plan = [p for p in PLAN if not want or p[0] in want or p[0] == "none"]
        print()
        print("=" * 78)
        print("PART 2/4 -- MUTATE, AND MUTATE-AND-REGENERATE, on the repaired "
              "gate")
        print("=" * 78)
        rows = []
        for case, mutation, regen in plan:
            desc = (MUTATIONS[mutation]["desc"] if mutation
                    else "unmutated instrument")
            print()
            print("-" * 78)
            print(f"CASE  {case:<16} regenerate={regen}")
            print(f"      {desc}")
            print("-" * 78)
            r = run_case(case, mutation, regen)
            r["regenerate"] = regen
            r["desc"] = desc
            exp = EXPECTED.get(case)
            r["expected_exit"] = exp
            for line in r["gate_failures"][:3]:
                print(f"      GATE FAILURE: {line[:150]}")
            if not r["gate_failures"]:
                print("      (no gate failure reported)")
            if r["regenerated"] and r["regenerated"].get("ok"):
                print(f"      regenerated rows: "
                      f"{len(r['regenerated']['rows'])}")
            verdict = ("OK" if exp is None or r["exit"] == exp
                       else "DISAGREES WITH THE AUDIT'S PREDICTION")
            print(f"      --> exit {r['exit']} "
                  f"(predicted {exp if exp is not None else 'measured'})  "
                  f"{verdict}")
            if r["exit"] > 1:
                failures.append(f"PART 2: {case} crashed (exit {r['exit']}); "
                                f"the run is not a measurement:\n"
                                f"{r['stderr_tail'][-600:]}")
            elif exp is not None and r["exit"] != exp:
                failures.append(
                    f"PART 2: {case} exited {r['exit']}, the audit predicted "
                    f"{exp}.  If this went 0 -> 1 a defect was REPAIRED and "
                    f"the row should be re-pointed, not deleted")
            rows.append(r)
        report["part2_matrix"] = rows

        print()
        print("=" * 78)
        print("THE MATRIX -- mg-4f9b's repaired gate, with and without "
              "regeneration")
        print("=" * 78)
        print(f"  {'case':<18} {'exit':>5}  what it means")
        for r in rows:
            if r["case"] == "none":
                meaning = ""
            elif r["exit"] == 1:
                meaning = "CAUGHT"
            elif r["regenerate"]:
                meaning = ("ABSORBED -- the reference was regenerated with "
                           "the mutation")
            else:
                meaning = "ABSORBED -- no control compares this quantity"
            print(f"  {r['case']:<18} {r['exit']:>5}  {meaning}")

    outp = os.path.join(REPO, "data", "onethird-mg56be-provenance-audit.json")
    with open(outp, "w") as f:
        json.dump(report, f, indent=1, sort_keys=True)
    print(f"\nwrote {os.path.relpath(outp, REPO)}")

    if failures:
        print("\nAUDIT ASSERTIONS THAT FAILED:")
        for p in failures:
            print(f"  - {p}")
        return 1
    print("\nEvery audit assertion holds on this tree.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
